#!/usr/bin/env bash

APP_NAME="Lorvex"
APP_PRODUCT_NAME="LorvexApple"
# User-facing name is "Lorvex" on every platform. The SwiftPM product/target
# name (LorvexApple), bundle id (com.lorvex.apple), and iCloud container
# (iCloud.com.lorvex.apple) carry the platform distinction where Apple
# Developer / CloudKit require unique identifiers.
APP_DISPLAY_NAME="Lorvex"
MOBILE_APP_NAME="LorvexMobileApp"
MOBILE_APP_DISPLAY_NAME="Lorvex"
VISION_APP_NAME="LorvexVisionApp"
VISION_APP_DISPLAY_NAME="Lorvex"
WATCH_APP_NAME="LorvexWatchApp"
WATCH_APP_DISPLAY_NAME="Lorvex"
WATCH_COMPLICATION_PRODUCT="LorvexWatchComplication"
WATCH_COMPLICATION_BUNDLE_ID="com.lorvex.apple.watchkitapp.widgets"
WATCH_COMPLICATION_KIND="com.lorvex.apple.watchkitapp.widgets.focus"
WATCH_COMPLICATION_DISPLAY_NAME="Lorvex Focus"
MCP_HOST_PRODUCT="LorvexMCPHost"
MCP_HOST_BUNDLE_ID="com.lorvex.apple.mcp-host"
MCP_SERVER_NAME="lorvex"
BUNDLE_ID="com.lorvex.apple"
MOBILE_BUNDLE_ID="com.lorvex.apple"
VISION_BUNDLE_ID="com.lorvex.apple.vision"
WATCH_BUNDLE_ID="com.lorvex.apple.watchkitapp"
WIDGET_BUNDLE_ID="com.lorvex.apple.focuswidget"
WIDGET_EXECUTABLE="LorvexFocusWidget"
WIDGET_APPEX_NAME="LorvexFocusWidget.appex"
WIDGET_KIND="com.lorvex.apple.widget.focus"
WIDGET_DISPLAY_NAME="Lorvex Focus"
WIDGET_DESCRIPTION="Shows today's focus plan from Lorvex."
WIDGET_EXTENSION_POINT_IDENTIFIER="com.apple.widgetkit-extension"
FOCUS_FILTER_BUNDLE_ID="com.lorvex.apple.focus-filter"
FOCUS_FILTER_EXECUTABLE="LorvexFocusFilterExtension"
FOCUS_FILTER_APPEX_NAME="LorvexFocusFilterExtension.appex"
FOCUS_FILTER_EXTENSION_POINT_IDENTIFIER="com.apple.appintents-extension"
CONTROL_WIDGET_KIND="com.lorvex.control.focus"
CONTROL_WIDGET_DISPLAY_NAME="Lorvex Focus"
CONTROL_WIDGET_DESCRIPTION="Shows the current focus task."
APP_GROUP_ID="group.com.lorvex.apple"
CLOUDKIT_CONTAINER_ID="iCloud.com.lorvex.apple"
MARKETING_VERSION="1.0.0"
BUILD_VERSION="2"
MIN_SYSTEM_VERSION="15.0"
MIN_MOBILE_SYSTEM_VERSION="18.0"
MIN_VISION_SYSTEM_VERSION="2.0"
MIN_WATCH_SYSTEM_VERSION="11.0"
URL_SCHEME="lorvex"
APP_CATEGORY="public.app-category.productivity"
CALENDAR_WRITE_USAGE_DESCRIPTION="Lorvex can add planning blocks you create to Apple Calendar."
CALENDAR_FULL_ACCESS_USAGE_DESCRIPTION="Lorvex can read event details to build schedules and assistant context."
