use crate::error::McpError;
use rusqlite::Connection;
use std::collections::HashSet;

// ── Shared helpers for ID-existence validators ──────────────────────
//
// `validate_task_ids_active` and `validate_list_ids_exist` both dedup
// the caller's input (preserving insertion order so the first missing
// id is reported in caller order) and build a comma-joined `?`
// placeholder string for an `IN (...)` SQL clause. The shared helpers
// below own that boilerplate so each per-entity validator stays a
// thin call site.

/// Dedup `ids` while preserving insertion order. Returns &str views into
/// the original slice so callers can route the result straight into
/// `rusqlite::params_from_iter` without copying.
fn dedup_preserve_order(ids: &[String]) -> Vec<&str> {
    let mut seen = HashSet::with_capacity(ids.len());
    ids.iter()
        .map(String::as_str)
        .filter(|id| seen.insert(*id))
        .collect()
}

// ── Circular dependency detection ───────────────────────────────────

// ── String length validation ────────────────────────────────────────
//
// Re-export the domain validators so call sites can keep using the
// short `validate_string_length(...)?` shape; `?` already converts
// `Result<(), ValidationError>` to `Result<(), McpError>` via the
// existing `From<ValidationError>` impl on `McpError`.
pub(crate) use lorvex_domain::validation::{
    validate_optional_string_length, validate_string_length,
};

/// Scrub an optional user-authored text field and re-run its length
/// validator after normalization. Callers that already use derive/manual
/// contract validation keep that first-pass guard; this closes the
/// post-sanitize boundary where NFC or control stripping can change the final
/// persisted string.
pub(crate) fn sanitize_optional_user_text(
    value: Option<String>,
    field_name: &'static str,
    max_len: usize,
) -> Result<Option<String>, McpError> {
    let sanitized = value.map(|text| lorvex_domain::sanitize_user_text(&text));
    validate_optional_string_length(sanitized.as_deref(), field_name, max_len)?;
    Ok(sanitized)
}

/// Verify that a list_id references an existing list, if provided.
pub(crate) fn validate_list_exists(
    conn: &Connection,
    list_id: Option<&str>,
) -> Result<(), McpError> {
    let Some(lid) = list_id else {
        return Ok(());
    };
    let typed = lorvex_domain::ListId::from_trusted(lid.to_string());
    Ok(lorvex_store::validate_task_list_exists(conn, &typed)?)
}

/// Resolve the canonical list for normal task creation.
///
/// Ordinary task creation must land in a real user list. The resolution
/// order is: (1) explicit `list_id`, (2) `default_list_id` preference.
/// Re-exported under the short path so call sites stay terse; `?`
/// already converts `StoreError` to `McpError` via the existing `From`
/// impl.
#[cfg(test)]
pub(crate) use lorvex_store::resolve_required_task_list_id;

/// Verify an ID looks like a hyphenated UUID so an obviously-bogus
/// caller argument ("task-1234", a title, empty string, etc.) fails
/// fast with an actionable "invalid UUID format" message instead of
/// a terse "non-existent task" after a DB round-trip. Accepts any
/// UUID version — we do not gate on v7 because historical IDs
/// generated by prior versions of the app may exist in synced data
/// and should remain lookupable.
///
/// Thin wrapper over the canonical
/// [`lorvex_domain::entity_id::parse_id_with_sentinel`]. The MCP
/// trust boundary has no sentinel cases (the inbox sentinel is
/// list-only and the MCP `list_id` arguments flow through
/// `resolve_required_task_list_id`, not this helper), so the
/// sentinel argument is always `None`. Trimming and the
/// empty-after-trim case both run here so whitespace-padded garbage
/// fails fast with a clearer message before hitting SQL.
pub(crate) fn validate_uuid_arg(id: &str, field_name: &'static str) -> Result<String, McpError> {
    use lorvex_domain::validation::ValidationError;
    match lorvex_domain::entity_id::parse_id_with_sentinel(id, field_name, None) {
        Ok(parsed) => Ok(parsed),
        Err(ValidationError::Empty(_)) => Err(McpError::Validation(format!(
            "{field_name} must not be empty"
        ))),
        Err(ValidationError::InvalidFormat { actual, .. }) => Err(McpError::Validation(format!(
            "{field_name} is not a valid UUID: '{actual}'"
        ))),
        Err(other) => Err(McpError::Validation(other.to_string())),
    }
}

pub(crate) fn validate_uuid_shape(id: &str, field_name: &'static str) -> Result<(), McpError> {
    validate_uuid_arg(id, field_name).map(|_| ())
}

/// Configuration for [`validate_ids_referencing`]. Each field below
/// describes one axis the three concrete validators differ on.
struct IdsValidatorOpts {
    /// Target table to query (`tasks`, `lists`, …).
    table: &'static str,
    /// Singular human-readable entity label embedded in error messages
    /// ("task", "list", …).
    entity_label: &'static str,
    /// When `true`, every id is run through `validate_uuid_shape` before
    /// any DB query — surfaces a hallucinated `"task-1234"`-shaped id
    /// with a clearer error than a post-DB "not found" miss.
    check_uuid_shape: bool,
    /// When `true`, the SELECT also reads `archived_at` and rejects
    /// archived (soft-deleted) rows with a distinct error message
    /// pointing the assistant at the Trash. The forward-planning
    /// surfaces (current focus, daily plan) need this; the dependency
    /// surface, which CAN reference archived rows, does not.
    reject_archived: bool,
}

/// Shared engine for ID-referenced existence (and optional archive)
/// validators. Encapsulates the dedup + single-IN-query + first-missing
/// detection that `validate_task_ids_active` and
/// `validate_list_ids_exist` share; the per-entity validators differ
/// only on table name and whether `archived_at` is selected.
fn validate_ids_referencing(
    conn: &Connection,
    ids: &[String],
    field_name: &'static str,
    opts: IdsValidatorOpts,
) -> Result<(), McpError> {
    for id in ids {
        if id.is_empty() {
            return Err(McpError::Validation(format!(
                "{field_name} contains an empty {} ID",
                opts.entity_label
            )));
        }
        if opts.check_uuid_shape {
            validate_uuid_shape(id, field_name)?;
        }
    }
    if ids.is_empty() {
        return Ok(());
    }

    let deduped = dedup_preserve_order(ids);
    let placeholders = lorvex_domain::sql_csv_placeholders(deduped.len());
    let sql = if opts.reject_archived {
        format!(
            "SELECT id, archived_at FROM {table} WHERE id IN ({placeholders})",
            table = opts.table,
        )
    } else {
        format!(
            "SELECT id FROM {table} WHERE id IN ({placeholders})",
            table = opts.table,
        )
    };
    let params = rusqlite::params_from_iter(deduped.iter().copied());
    let mut stmt = conn.prepare(&sql)?;

    if opts.reject_archived {
        let mut existing: std::collections::HashMap<String, Option<String>> =
            std::collections::HashMap::with_capacity(deduped.len());
        let rows = stmt.query_map(params, |row| {
            Ok((row.get::<_, String>(0)?, row.get::<_, Option<String>>(1)?))
        })?;
        for row in rows {
            let (id, archived_at) = row?;
            existing.insert(id, archived_at);
        }
        for id in ids {
            match existing.get(id.as_str()) {
                None => {
                    return Err(McpError::Validation(format!(
                        "{field_name} references non-existent {entity} '{id}'",
                        entity = opts.entity_label,
                    )));
                }
                Some(Some(_)) => {
                    return Err(McpError::Validation(format!(
                        "{field_name} references archived (trashed) {entity} '{id}'; restore it from Trash before adding it to focus",
                        entity = opts.entity_label,
                    )));
                }
                Some(None) => {}
            }
        }
    } else {
        let existing: HashSet<String> = stmt
            .query_map(params, |row| row.get::<_, String>(0))?
            .collect::<rusqlite::Result<_>>()?;
        if let Some(missing) = ids.iter().find(|id| !existing.contains(id.as_str())) {
            return Err(McpError::Validation(format!(
                "{field_name} references non-existent {entity} '{missing}'",
                entity = opts.entity_label,
            )));
        }
    }
    Ok(())
}

/// Verify that every task ID references a live, non-archived task.
///
/// `validate_task_ids_exist` only confirms the row is in the
/// `tasks` table — it accepts soft-deleted rows whose `archived_at` is
/// non-NULL. The current-focus surface is a forward-looking plan, so an
/// archived task ID is just as broken as a phantom one: every task read
/// path filters `archived_at IS NULL`, so the focus would render an
/// empty row that the user has no way to recover.
///
/// This helper folds existence + archive checks into a single query
/// and reports the first offending id in caller order. The error
/// message distinguishes the two failure modes so the assistant can
/// react appropriately (re-create vs. restore-from-trash).
pub(crate) fn validate_task_ids_active(
    conn: &Connection,
    task_ids: &[String],
    field_name: &'static str,
) -> Result<(), McpError> {
    validate_ids_referencing(
        conn,
        task_ids,
        field_name,
        IdsValidatorOpts {
            table: "tasks",
            entity_label: "task",
            check_uuid_shape: true,
            reject_archived: true,
        },
    )
}

/// Verify that all list IDs in the array reference existing lists.
///
/// Validates `linked_list_ids` for the daily-review write path before
/// they reach the join-table materializer, so a phantom list ID never
/// lands in `daily_review_lists`. Routes through the shared dedup +
/// single-IN-query engine so a 20-list payload costs one round-trip.
pub(crate) fn validate_list_ids_exist(
    conn: &Connection,
    list_ids: &[String],
    field_name: &'static str,
) -> Result<(), McpError> {
    validate_ids_referencing(
        conn,
        list_ids,
        field_name,
        IdsValidatorOpts {
            table: "lists",
            entity_label: "list",
            check_uuid_shape: false,
            reject_archived: false,
        },
    )
}

#[cfg(test)]
mod tests {
    //! Tests for MCP task validation. Extracted from the parent file to keep
    //! the production module focused.

    use super::*;
    use rusqlite::Connection;

    fn setup_test_conn() -> Connection {
        let conn = Connection::open_in_memory().expect("open in-memory db");
        lorvex_store::migration::apply_migrations(&conn, &lorvex_store::schema::all_migrations())
            .expect("apply migrations");
        conn
    }

    #[test]
    fn validate_list_exists_accepts_none() {
        let conn = setup_test_conn();
        assert!(validate_list_exists(&conn, None).is_ok());
    }

    #[test]
    fn validate_list_exists_rejects_missing() {
        let conn = setup_test_conn();
        let result = validate_list_exists(&conn, Some("nonexistent-id"));
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("does not exist"));
    }

    #[test]
    fn validate_list_exists_accepts_existing() {
        let conn = setup_test_conn();
        lorvex_store::test_support::ListBuilder::new("lst1")
            .name("Test")
            .insert(&conn);
        assert!(validate_list_exists(&conn, Some("lst1")).is_ok());
    }

    #[test]
    fn validate_list_exists_rejects_empty() {
        let conn = setup_test_conn();
        let result = validate_list_exists(&conn, Some(""));
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("must not be empty"));
    }

    #[test]
    fn resolve_required_task_list_id_prefers_explicit() {
        let conn = setup_test_conn();
        lorvex_store::test_support::ListBuilder::new("lst1")
            .name("Explicit")
            .insert(&conn);

        assert_eq!(
            resolve_required_task_list_id(&conn, Some("lst1")).unwrap(),
            "lst1"
        );
    }

    #[test]
    fn resolve_required_task_list_id_uses_default_preference() {
        let conn = setup_test_conn();
        lorvex_store::test_support::ListBuilder::new("lst1")
            .name("Default")
            .insert(&conn);
        conn.execute(
        "INSERT OR REPLACE INTO preferences (key, value, version, updated_at) VALUES (?1, ?2, ?3, datetime('now'))",
        rusqlite::params![
            lorvex_domain::preference_keys::PREF_DEFAULT_LIST_ID,
            "\"lst1\"",
            "0000000000000_0000_0000000000000000",
        ],
    )
    .unwrap();

        assert_eq!(resolve_required_task_list_id(&conn, None).unwrap(), "lst1");
    }

    #[test]
    fn resolve_required_task_list_id_rejects_nested_quoted_preference() {
        let conn = setup_test_conn();
        lorvex_store::test_support::ListBuilder::new("lst1")
            .name("Default")
            .insert(&conn);
        conn.execute(
        "INSERT OR REPLACE INTO preferences (key, value, version, updated_at) VALUES (?1, ?2, ?3, datetime('now'))",
        rusqlite::params![
            lorvex_domain::preference_keys::PREF_DEFAULT_LIST_ID,
            "\"\\\"lst1\\\"\"",
            "0000000000000_0000_0000000000000000",
        ],
    )
    .unwrap();

        let error = resolve_required_task_list_id(&conn, None)
            .expect_err("double-encoded default list preference should fail");
        assert!(
            error
                .to_string()
                .contains("default_list_id preference must be a JSON string"),
            "unexpected error: {error}"
        );
    }

    // ── String length validation tests ──────────────────────────────

    #[test]
    fn validate_string_length_accepts_within_limit() {
        assert!(validate_string_length("hello", "title", 10).is_ok());
    }

    #[test]
    fn validate_string_length_accepts_exact_limit() {
        assert!(validate_string_length("12345", "title", 5).is_ok());
    }

    #[test]
    fn validate_string_length_rejects_over_limit() {
        let result = validate_string_length("123456", "title", 5);
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("title"));
        assert!(err.contains("6 chars"));
        assert!(err.contains("limit 5"));
    }

    #[test]
    fn validate_optional_string_length_accepts_none() {
        assert!(validate_optional_string_length(None, "body", 10).is_ok());
    }

    #[test]
    fn validate_optional_string_length_rejects_over_limit() {
        let result = validate_optional_string_length(Some("toolong"), "body", 3);
        assert!(result.is_err());
    }

    // Cycle-detection tests live in lorvex_workflow::dependency_validation::tests.
    // The delegate wrapper is covered by the remaining integration tests that exercise
    // task creation and update flows end-to-end.

    // ── validate_task_ids_active (#2888 archived rejection) ─────────

    /// Three fixed UUIDv7-shaped strings the ID tests reuse. Pinned
    /// rather than generated so the "first missing in caller order"
    /// assertion can reference a specific literal.
    const TEST_UUID_1: &str = "01966a3f-7c8b-7d4e-8f3a-000000000001";
    const TEST_UUID_2: &str = "01966a3f-7c8b-7d4e-8f3a-000000000002";
    const TEST_UUID_3: &str = "01966a3f-7c8b-7d4e-8f3a-000000000003";

    fn insert_task_helper(conn: &Connection, id: &str, archived_at: Option<&str>) {
        // lift to canonical TaskBuilder.
        lorvex_store::test_support::fixtures::TaskBuilder::new(id)
            .title("T")
            .archived_at(archived_at)
            .insert(conn);
    }

    #[test]
    fn validate_task_ids_active_accepts_live_task() {
        let conn = setup_test_conn();
        insert_task_helper(&conn, TEST_UUID_1, None);
        let ids = vec![TEST_UUID_1.to_string()];
        assert!(validate_task_ids_active(&conn, &ids, "task_ids").is_ok());
    }

    #[test]
    fn validate_task_ids_active_rejects_nonexistent_id() {
        let conn = setup_test_conn();
        let ids = vec![TEST_UUID_1.to_string()];
        let err = validate_task_ids_active(&conn, &ids, "task_ids").unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("non-existent task"), "unexpected error: {msg}");
        assert!(msg.contains(TEST_UUID_1), "missing id in message: {msg}");
    }

    #[test]
    fn validate_task_ids_active_rejects_archived_task() {
        let conn = setup_test_conn();
        insert_task_helper(&conn, TEST_UUID_1, Some("2026-04-26T00:00:00.000Z"));
        let ids = vec![TEST_UUID_1.to_string()];
        let err = validate_task_ids_active(&conn, &ids, "task_ids").unwrap_err();
        let msg = err.to_string();
        assert!(msg.contains("archived"), "unexpected error: {msg}");
        assert!(msg.contains(TEST_UUID_1), "missing id in message: {msg}");
    }

    #[test]
    fn validate_task_ids_active_mixed_batch_reports_first_offender_in_caller_order() {
        let conn = setup_test_conn();
        // TEST_UUID_1 is live; TEST_UUID_2 is archived; TEST_UUID_3 is missing.
        insert_task_helper(&conn, TEST_UUID_1, None);
        insert_task_helper(&conn, TEST_UUID_2, Some("2026-04-26T00:00:00.000Z"));
        let ids = vec![
            TEST_UUID_1.to_string(),
            TEST_UUID_2.to_string(),
            TEST_UUID_3.to_string(),
        ];
        let err = validate_task_ids_active(&conn, &ids, "task_ids").unwrap_err();
        let msg = err.to_string();
        // Caller order: live → archived → missing. First offender is the
        // archived one.
        assert!(msg.contains("archived"), "expected archived error: {msg}");
        assert!(msg.contains(TEST_UUID_2), "expected #2 id: {msg}");
        assert!(
            !msg.contains(TEST_UUID_3),
            "should not report later phantom: {msg}"
        );
    }

    #[test]
    fn validate_task_ids_active_accepts_empty_list() {
        let conn = setup_test_conn();
        assert!(validate_task_ids_active(&conn, &[], "task_ids").is_ok());
    }

    #[test]
    fn validate_task_ids_active_rejects_malformed_uuid() {
        let conn = setup_test_conn();
        let ids = vec!["not-a-uuid".to_string()];
        let err = validate_task_ids_active(&conn, &ids, "task_ids").unwrap_err();
        assert!(err.to_string().contains("not a valid UUID"));
    }
}
