import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

import { repoRoot } from './shared.mjs';

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');
}

test('Tauri distribution docs retire CloudKit schema ownership', () => {
  const distribution = read('docs/design/DISTRIBUTION.md');
  assert.equal(fs.existsSync(path.join(repoRoot, 'cloudkit/schema.ckdb')), false);
  assert.match(distribution, /Tauri CloudKit schema\/container can be abandoned/i);
});

test('Windows signing docs route local builds through the build script', () => {
  for (const relativePath of ['CLAUDE.md', 'docs/design/DISTRIBUTION.md']) {
    const source = read(relativePath);
    assert.match(source, /powershell -ExecutionPolicy Bypass -File scripts\/build_windows\.ps1 -Bundle nsis/);
    assert.doesNotMatch(source, /To sign locally, set `certificateThumbprint`/);
  }
});

test('Tauri command registration docs describe the generated handler wiring', () => {
  const contributing = read('CONTRIBUTING.md');

  assert.match(contributing, /`generate_handler!\[\]` list in `lib\.rs` is auto-generated by `app\/src-tauri\/build\.rs`/);
  assert.doesNotMatch(contributing, /Register every new command.*generate_handler!\[\]/);
});

test('architecture and contributor docs describe current workflow and Tauri error boundaries', () => {
  const contributing = read('CONTRIBUTING.md');
  const multiSurface = read('docs/design/MULTI_SURFACE_ARCHITECTURE.md');
  const workflowManifest = read('lorvex-workflow/Cargo.toml');
  const syncManifest = read('lorvex-sync/Cargo.toml');
  const mcpManifest = read('mcp-server/Cargo.toml');
  const appErrorBoundary = read('app/src-tauri/src/error/boundary.rs');
  const appErrorEnvelope = read('app/src-tauri/src/error/envelope.rs');

  assert.match(workflowManifest, /name = "lorvex-workflow"/);
  assert.match(syncManifest, /lorvex-workflow = \{ path = "\.\.\/lorvex-workflow" \}/);
  assert.match(mcpManifest, /lorvex-mcp-derive = \{ path = "\.\.\/lorvex-mcp-derive" \}/);

  assert.match(multiSurface, /Workflow \(lorvex-workflow\)/);
  assert.match(multiSurface, /canonical SQL mutations \+ business rules for App, CLI, MCP, and sync apply/);
  assert.match(multiSurface, /compile-time codegen only, consumed by mcp-server/);
  assert.doesNotMatch(multiSurface, /lorvex-store\/\s+SQLite storage layer\s*$/m);

  assert.match(appErrorBoundary, /impl From<AppError> for String/);
  assert.match(appErrorEnvelope, /Wire-format error envelope returned across the Tauri IPC boundary/);
  assert.match(contributing, /`AppResult<T>` \/ `AppError`/);
  assert.match(contributing, /`app\/src-tauri\/src\/error\/boundary\.rs`/);
  assert.match(contributing, /`app\/src-tauri\/src\/error\/envelope\.rs`/);
  assert.match(contributing, /Do not teach or copy bare `\.map_err\(\|e\| e\.to_string\(\)\)` for Tauri commands/);
});

test('runtime and sync docs mirror current local-state table names', () => {
  const schema = read('lorvex-store/src/schema/001_schema.sql');
  const localStateRuntime = read('lorvex-runtime/src/local_state/mod.rs');
  const docs = [
    ['DATA_MODEL', read('docs/design/DATA_MODEL.md')],
    ['MULTI_SURFACE_ARCHITECTURE', read('docs/design/MULTI_SURFACE_ARCHITECTURE.md')],
    ['SYNC_RUNTIME', read('docs/design/naming/SYNC_RUNTIME.md')],
  ];

  assert.match(schema, /CREATE TABLE IF NOT EXISTS sync_pending_inbox \(/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS local_counters \(/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS mcp_host_authority \(/);
  assert.match(localStateRuntime, /local_counters/);
  assert.match(localStateRuntime, /mcp_host_authority/);

  for (const [label, source] of docs) {
    assert.doesNotMatch(source, /\blocal_runtime_state\b/, `${label} should not reference the deleted local_runtime_state table`);
    assert.doesNotMatch(source, /\bsync_inbox\b/, `${label} should not reference the nonexistent sync_inbox table`);
  }

  const combinedDocs = docs.map(([, source]) => source).join('\n');
  assert.match(combinedDocs, /\blocal_counters\b/);
  assert.match(combinedDocs, /\bsync_pending_inbox\b/);
  assert.match(combinedDocs, /\bmcp_host_authority\b/);
});

test('MCP idempotency docs mirror retry cache semantics', () => {
  const schema = read('lorvex-store/src/schema/001_schema.sql');
  const contract = read('mcp-server/src/contract.rs');
  const dataModel = read('docs/design/DATA_MODEL.md');
  const mcpTools = read('docs/design/MCP_TOOLS.md');
  const setup = read('docs/setup/ASSISTANT_MCP_SETUP.md');

  assert.match(schema, /CREATE TABLE IF NOT EXISTS mcp_idempotency \(/);
  assert.match(schema, /PRIMARY KEY \(tool_name, key\)/);
  assert.match(schema, /\brequest_checksum\b/);
  assert.match(schema, /Rows expire 24h after creation/);
  assert.match(contract, /IDEMPOTENCY_KEY_DESCRIPTION/);
  assert.match(contract, /reuse the same key/);
  assert.match(contract, /cached response for ~24h/);

  for (const [label, source] of [
    ['DATA_MODEL', dataModel],
    ['MCP_TOOLS', mcpTools],
    ['ASSISTANT_MCP_SETUP', setup],
  ]) {
    assert.match(source, /\bmcp_idempotency\b/, `${label} should name the retry cache table`);
    assert.match(source, /\bidempotency_key\b/, `${label} should document the client token`);
    assert.match(source, /\brequest_checksum\b/, `${label} should document mismatch detection`);
    assert.match(source, /24h|24 hours|~24h/, `${label} should document the retention window`);
    assert.match(source, /cached response|replay/i, `${label} should document retry replay behavior`);
  }
});

test('vision copy distinguishes curated focus UI from persisted current_focus state', () => {
  const schema = read('lorvex-store/src/schema/001_schema.sql');
  const dataModel = read('docs/design/DATA_MODEL.md');
  const philosophy = read('docs/vision/DESIGN_PHILOSOPHY.md');
  const pitch = read('docs/vision/PITCH_EN.md');

  assert.match(schema, /CREATE TABLE IF NOT EXISTS current_focus \(/);
  assert.match(dataModel, /### current_focus \(Today's Focus\)/);

  assert.match(philosophy, /curated presentation over persisted planning state, not a raw table browser/i);
  assert.match(philosophy, /not just a passive persistence viewer/i);
  assert.match(pitch, /clean briefing over saved focus state, not a spreadsheet-style management grid/i);
  for (const [label, source] of [
    ['DESIGN_PHILOSOPHY', philosophy],
    ['PITCH_EN', pitch],
  ]) {
    assert.doesNotMatch(source, /not a database table/i, `${label} should not deny persisted focus state`);
    assert.doesNotMatch(source, /not a database view/i, `${label} should not deny persisted focus state`);
    assert.doesNotMatch(source, /not just a database viewer/i, `${label} should not deny persisted focus state`);
  }
});

test('active docs describe the current pre-public-release schema compatibility policy consistently', () => {
  const readme = read('README.md');
  const contributing = read('CONTRIBUTING.md');
  const claude = read('CLAUDE.md');
  const dataModel = read('docs/design/DATA_MODEL.md');
  const distribution = read('docs/design/DISTRIBUTION.md');

  for (const [label, source] of [
    ['README', readme],
    ['CONTRIBUTING', contributing],
    ['CLAUDE', claude],
    ['DATA_MODEL', dataModel],
  ]) {
    assert.match(
      source,
      /pre-public-release/i,
      `${label} should name the current pre-public-release schema policy`,
    );
  }

  assert.match(readme, /not a current data-format compatibility guarantee/i);
  assert.match(contributing, /not a data-format stability guarantee/i);
  assert.match(claude, /pre-public-release schema policy/i);
  assert.match(dataModel, /single squashed baseline/i);
  assert.match(dataModel, /Future post-public-release/i);
  assert.match(distribution, /Packaging identity stability only/i);

  for (const [label, source] of [
    ['README', readme],
    ['CONTRIBUTING', contributing],
    ['CLAUDE', claude],
    ['DATA_MODEL', dataModel],
    ['DISTRIBUTION', distribution],
  ]) {
    assert.doesNotMatch(
      source,
      /1\.0\.0\s*=\s*stable, data format compatibility guaranteed/i,
      `${label} must not claim the current package version guarantees data-format compatibility`,
    );
  }
});

test('DATA_MODEL distinguishes public list deletion APIs from the schema re-home safety trigger', () => {
  const dataModel = read('docs/design/DATA_MODEL.md');
  const schema = read('lorvex-store/src/schema/001_schema.sql');
  const mcpDelete = read('mcp-server/src/lists/mutations/delete/mod.rs');

  assert.match(schema, /CREATE TRIGGER IF NOT EXISTS trg_lists_before_delete/);
  assert.match(schema, /UPDATE tasks SET list_id = 'inbox' WHERE list_id = OLD\.id AND OLD\.id != 'inbox'/);
  assert.match(schema, /OLD\.id = 'inbox' AND EXISTS \(SELECT 1 FROM tasks LIMIT 1\)/);
  assert.match(mcpDelete, /count_assigned_tasks_in_list/);
  assert.match(mcpDelete, /Cannot delete list [\s\S]*while \{assigned_task_count\} task\(s\) are still assigned/);

  assert.match(dataModel, /public list deletion APIs/i);
  assert.match(dataModel, /blocked until assigned tasks are moved or\s+permanently deleted/i);
  assert.match(dataModel, /`trg_lists_before_delete`/);
  assert.match(dataModel, /sync\/direct-SQL safety net/i);
  assert.match(dataModel, /re-homes non-inbox list deletes to `inbox`/i);
  assert.match(dataModel, /blocks\s+inbox deletion while live tasks exist/i);
});

test('calendar behavior docs distinguish Lorvex-owned canonical events from provider mirrors', () => {
  const calendarBehavior = read('docs/design/CALENDAR_BEHAVIOR.md');
  const features = read('docs/design/FEATURES.md');
  const docsIndex = read('docs/INDEX.md');

  assert.match(calendarBehavior, /`calendar_events` are Lorvex-owned canonical events/i);
  assert.match(calendarBehavior, /create, edit, delete, link, and export canonical events/i);
  assert.match(calendarBehavior, /`provider_calendar_events` are read-only external provider mirrors/i);
  assert.match(calendarBehavior, /Provider events stay read-only/i);
  assert.doesNotMatch(calendarBehavior, /read-projected `calendar_events`/i);
  assert.doesNotMatch(calendarBehavior, /Calendar events are \*\*read-only renders of external sources\*\*/i);

  assert.match(docsIndex, /\[CALENDAR_BEHAVIOR\.md\]\(design\/CALENDAR_BEHAVIOR\.md\)/);
  assert.match(features, /\[Calendar behavior\]\(CALENDAR_BEHAVIOR\.md\)/);
});

test('copy guidelines point at configurable strict-parity JSON catalogs', () => {
  const copyGuide = read('docs/design/COPY_GUIDELINES.md');

  assert.match(copyGuide, /`en\.json`[\s\S]*`app\/src\/locales\/strict-parity\.json`/);
  assert.match(copyGuide, /strict-?parity/i);
  assert.doesNotMatch(copyGuide, /`en\.ts`|`zh\.ts`/);
  assert.doesNotMatch(copyGuide, /Non-English locale files may remain partial during iteration/);
});

test('feature docs describe Quick Capture as a local Tauri IPC write path', () => {
  const features = read('docs/design/FEATURES.md');

  assert.match(features, /Quick capture: local Tauri IPC write/i);
  assert.match(features, /same domain\/store invariants as MCP writes/i);
  assert.doesNotMatch(features, /Quick Capture sends to (?:the )?AI assistant/i);
  assert.doesNotMatch(features, /Quick Capture sends .*MCP/i);
});

test('Tauri does not keep App Store privacy docs', () => {
  for (const relativePath of [
    'docs/appstore/PRIVACY.md',
    'docs/appstore/privacy_labels.md',
    'docs/appstore/review_notes.md',
  ]) {
    assert.equal(fs.existsSync(path.join(repoRoot, relativePath)), false);
  }
});

test('feature docs mirror shipped shortcuts, font scale labels, and HTTPS-only ICS subscription validation', () => {
  const features = read('docs/design/FEATURES.md');

  assert.match(features, /global shortcut \(Cmd\/Ctrl\+N\)/);
  assert.doesNotMatch(features, /⌘⇧Space/);

  assert.match(features, /Small \/ Compact \/ Default \/ Large \/ Extra Large/);
  assert.doesNotMatch(features, /Small \/ Default \/ Medium \/ Large \/ X-Large/);

  assert.match(features, /URL scheme validation \(https:\/\/ only\)/);
  assert.doesNotMatch(features, /https\/http only|http\/https|webcal/i);
});

test('architecture docs route Apple mobile work to Swift and leave Android planned for Tauri', () => {
  const architecture = read('docs/design/ARCHITECTURE.md');

  assert.match(architecture, /iOS and\s+iPadOS now belong to the Swift app under `apps\/apple`/i);
  assert.match(architecture, /Android remains the\s+only planned Tauri mobile runtime/i);
  assert.doesNotMatch(architecture, /iOS is now an active reduced-capability peer runtime/i);
});

test('platform docs align Windows Hello and retired Apple mobile status with runtime capability truth', () => {
  const readme = read('README.md');
  const roadmap = read('ROADMAP.md');
  const architecture = read('docs/design/ARCHITECTURE.md');
  const multiSurface = read('docs/design/MULTI_SURFACE_ARCHITECTURE.md');
  const platformMatrix = read('docs/design/PLATFORM_CAPABILITY_MATRIX.md');
  const platformLogic = read('app/src/lib/platform/platform.logic.ts');
  const schema = read('lorvex-store/src/schema/001_schema.sql');

  assert.match(
    platformLogic,
    /windows:\s*\{[\s\S]*supportsBiometricLock:\s*true,[\s\S]*biometricAdapterKind:\s*'windows_hello'/,
    'runtime profile should expose active Windows Hello biometric support',
  );
  assert.match(platformMatrix, /\| Biometrics \| yes \| yes \| target varies \| target yes \| [^\n]*Windows Hello/i);
  assert.match(
    roadmap,
    /- \[x\] Windows Hello biometric lock \(Windows Hello via `windows` crate WebAuthN\/Credential API\)/,
    'ROADMAP should list Windows Hello under shipped platform work',
  );
  assert.doesNotMatch(roadmap, /- \[ \] Windows Hello biometrics/i);

  assert.doesNotMatch(platformMatrix, /\| iOS mobile runtime \|/);
  assert.match(
    readme,
    /native calendar imports via Windows Appointments and Linux local calendar\/ICS/i,
    'README should describe native calendar support on the Windows/Linux desktop line (EventKit removed from Tauri)',
  );
  assert.doesNotMatch(readme, /EventKit/i, 'Tauri README must not reference EventKit — the Apple-only framework is removed');
  assert.match(roadmap, /- \[x\] Native calendar reading \(Windows Appointments \+ Linux local calendar\/ICS provider mirror/);
  assert.doesNotMatch(roadmap, /EventKit/i, 'ROADMAP must not reference EventKit after the Tauri realignment');
  assert.match(architecture, /macOS reference build ships no native-calendar adapter; EventKit belongs to the Apple Swift app/);
  assert.doesNotMatch(architecture, /macOS calendar via EventKit \(active\)/);
  assert.doesNotMatch(architecture, /macOS\/iOS calendar via EventKit/);
  assert.doesNotMatch(multiSurface, /EventKit/, 'MULTI_SURFACE_ARCHITECTURE must not reference EventKit — removed from the Tauri line');

  assert.match(
    platformLogic,
    /android:\s*\{[\s\S]*supportsNativeCalendarRead:\s*false,[\s\S]*nativeCalendarAdapterKind:\s*'none',[\s\S]*nativeCalendarActivationState:\s*'none'/,
    'runtime profile should expose no Android native-calendar adapter contract yet',
  );
  assert.doesNotMatch(schema, /'android_calendar'/);
  assert.match(
    platformMatrix,
    /\| Native calendar read \| no \| yes \| yes \| no active contract \| [^\n]*Android needs an adapter kind/i,
    'capability matrix: macOS reference build has no native-calendar reader; Android stays no-active-contract while the adapter contract is absent',
  );
  assert.match(
    platformMatrix,
    /\| Android mobile runtime \| `none` \| no native-calendar adapter contract yet \| none \| define adapter kind, runtime profile, schema allowlists, and Android bridge before activation \|/,
    'platform matrix should not claim an Android adapter that runtime/schema reject',
  );
  assert.doesNotMatch(platformMatrix, /`android_calendar`|platform::android_calendar|CalendarReader\.kt|adapter implemented; Android/i);
});

test('roadmap and features retire Tauri WidgetKit scaffold ownership', () => {
  const roadmap = read('ROADMAP.md');
  const features = read('docs/design/FEATURES.md');

  assert.match(features, /### Desktop Widget Surfaces \[CUT\]/);
  assert.match(features, /Apple WidgetKit surfaces belong to the Swift app under `apps\/apple`/);
  assert.doesNotMatch(roadmap, /WidgetKit widgets/i);
  assert.equal(fs.existsSync(path.join(repoRoot, 'app/src-tauri/gen/apple/project.yml')), false);
  assert.doesNotMatch(
    roadmap,
    /Future Exploration[\s\S]*WidgetKit companion/,
    'ROADMAP must not present partially shipped WidgetKit scaffold as a not-started future idea',
  );
});

test('design token docs name the canonical token verification gates', () => {
  const designTokens = read('docs/design/DESIGN_TOKENS.md');
  const packageJson = JSON.parse(read('package.json'));
  const verificationManifest = read('scripts/verify/verification_manifest.mjs');
  const requiredCommands = [
    'verify:theme-tokens',
    'verify:design-tokens-completeness',
    'verify:focus-ring-consistency',
    'verify:motion-reduce-redundancy',
  ];

  assert.match(designTokens, /npm run verify:frontend-static-contracts/);
  for (const command of requiredCommands) {
    assert.equal(typeof packageJson.scripts[command], 'string', `${command} should exist in package.json`);
    assert.match(verificationManifest, new RegExp(`npmScript\\('${command}'\\)`));
    assert.match(designTokens, new RegExp(`npm run ${command}`));
  }
});

test('Inbox docs distinguish removed review surfaces from seeded default-list bootstrap state', () => {
  const schema = read('lorvex-store/src/schema/001_schema.sql');
  const naming = read('docs/design/naming/TASK_SYSTEM.md');
  const vision = read('docs/vision/VISION.md');
  const philosophy = read('docs/vision/DESIGN_PHILOSOPHY.md');
  const pitch = read('docs/vision/PITCH_EN.md');
  const perViewContent = read('docs/design/PER_VIEW_CONTENT_STRATEGY.md');
  const claudeOperating = read('docs/design/CLAUDE_OPERATING_MODEL.md');
  const claudePrompt = read('docs/CLAUDE_PROMPT.md');
  const deepLinks = read('docs/setup/DEEP_LINK_URL_SCHEME.md');
  const claude = read('CLAUDE.md');

  assert.match(schema, /VALUES \('inbox', 'Inbox'/);
  assert.match(schema, /VALUES \('default_list_id', '"inbox"'/);

  assert.match(naming, /schema-seeded `inbox` default list/i);
  assert.match(naming, /`default_list_id`/);
  assert.match(naming, /bootstrap\/default-routing artifact/i);
  assert.match(naming, /not an active Inbox UI or review workflow/i);
  assert.match(naming, /schema, setup, tests, default-list routing, and historical docs/i);
  assert.doesNotMatch(naming, /it should not appear as a current canonical task-system concept/i);

  for (const [label, source] of [
    ['VISION', vision],
    ['DESIGN_PHILOSOPHY', philosophy],
    ['PITCH_EN', pitch],
    ['PER_VIEW_CONTENT_STRATEGY', perViewContent],
    ['CLAUDE_OPERATING_MODEL', claudeOperating],
    ['CLAUDE', claude],
  ]) {
    assert.match(
      source,
      /Inbox (?:UI\/review surface|review surface|UI\/review workflow) (?:was|has been) removed/i,
      `${label} should name the removed user-facing Inbox surface precisely`,
    );
    assert.match(
      source,
      /schema-seeded `inbox` default list|internal `inbox` seeded default list/i,
      `${label} should preserve the internal seeded default-list caveat`,
    );
    assert.doesNotMatch(
      source,
      /\b(?:the )?Inbox was removed\b|\bthe inbox was removed\b/i,
      `${label} should not imply every Inbox/default-list artifact was removed`,
    );
  }

  assert.match(claudePrompt, /`default_list_id` may point at the schema-seeded `inbox` list/i);
  assert.match(claudePrompt, /not an Inbox review queue or surface/i);
  assert.match(deepLinks, /default_list_id[\s\S]*schema-seeded `inbox` list/i);
  assert.match(deepLinks, /not an Inbox view or review workflow/i);
});

test('Deep-link URL scheme docs reflect review-first behavior', () => {
  const deepLinks = read('docs/setup/DEEP_LINK_URL_SCHEME.md');
  const navigation = read('app/src/app-shell/main-window/useMainWindowNavigation.ts');
  const parser = read('app/src-tauri/src/deep_link/parse.rs');

  assert.match(navigation, /openQuickCapture\(params \?/);
  assert.match(navigation, /navigateToView\(\{ type: 'today' \}\);[\s\S]*setSelectedTaskId\(taskId\);/);
  assert.match(parser, /add-task deep link priority must be an integer between 1 and 3/);

  assert.match(deepLinks, /opens Quick Capture prefilled for user review/i);
  assert.match(deepLinks, /does not create the task until the user submits Quick Capture/i);
  assert.match(deepLinks, /opens the task for manual completion confirmation/i);
  assert.match(deepLinks, /does not mark the task completed by itself/i);
  assert.match(deepLinks, /Invalid `priority` values .* reject the deep link/i);
  assert.doesNotMatch(deepLinks, /Create a new task/i);
  assert.doesNotMatch(deepLinks, /Mark a task as completed/i);
  assert.doesNotMatch(deepLinks, /silently ignored/i);
});

test('vision docs preserve shipped priority and list correction affordances', () => {
  const philosophy = read('docs/vision/DESIGN_PHILOSOPHY.md');
  const vision = read('docs/vision/VISION.md');
  const ux = read('docs/design/UX.md');
  const features = read('docs/design/FEATURES.md');
  const quickCapturePriority = read('app/src/components/quick-capture/toolbar/PriorityDropdown.tsx');
  const taskMetaCard = read('app/src/components/task-detail/metadata-editor/TaskUnifiedMetaCard.tsx');

  assert.match(quickCapturePriority, /ToggleChip[\s\S]*t\('task\.priority'\)/);
  assert.match(taskMetaCard, /aria-label=\{t\('task\.priority'\)\}/);
  assert.match(taskMetaCard, /aria-label=\{t\('task\.list'\)\}/);
  assert.match(features, /Quick capture:[^\n]*priority \(P1.*P3\)[^\n]*list assignment/i);

  for (const [label, source] of [
    ['DESIGN_PHILOSOPHY', philosophy],
    ['VISION', vision],
    ['UX', ux],
  ]) {
    assert.match(source, /AI-managed priority remains canonical/i, `${label} should keep AI priority as the default model`);
    assert.match(
      source,
      /human override and power-user controls are shipped correction affordances/i,
      `${label} should explicitly preserve shipped priority/list correction controls`,
    );
  }

  assert.doesNotMatch(philosophy, /Priority dropdown\s+.*removed \(AI sets priority\)/i);
  assert.doesNotMatch(philosophy, /No manual priority setting \(AI computes\)\. No manual list assignment \(AI infers\)/i);
  assert.doesNotMatch(vision, /AI set the priority\s+.*you don't need a priority dropdown/i);
  assert.doesNotMatch(vision, /AI assigned the list\s+.*you don't need a list picker/i);
  assert.doesNotMatch(ux, /No priority dropdowns \(AI set it\)/i);
});

test('command palette docs list the shipped system action registry', () => {
  const commandPalette = read('docs/design/COMMAND_PALETTE.md');
  const systemActions = read('app/src/components/command-palette/controller/systemActions.logic.ts');
  const ids = Array.from(new Set(
    Array.from(systemActions.matchAll(/id: '(system\.[^']+)'/g), (match) => match[1]),
  ));

  assert.ok(ids.length > 0, 'system action registry should expose stable ids');
  assert.match(commandPalette, /systemActions\.logic\.ts/);
  for (const id of ids) {
    assert.match(commandPalette, new RegExp(`\\\`${id}\\\``), `COMMAND_PALETTE.md should document ${id}`);
  }
});
