#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const START_MARKER = '<!-- DOC_INVENTORY:START -->';
const END_MARKER = '<!-- DOC_INVENTORY:END -->';
const GROUP_ORDER = [
  'root',
  'vision',
  'design',
  'execution',
  'reference',
  'setup',
  'plans',
];
const AUTO_INVENTORY_EXCLUDED_GROUPS = new Set(['archive', 'decisions', 'plans', 'rfcs', 'superpowers']);

function isDatedExecutionReport(relativePath) {
  return /^execution\/20\d{2}-\d{2}-\d{2}-.*\.md$/.test(relativePath);
}

function shouldIncludeInAutoInventory(relativePath) {
  const group = getGroup(relativePath);
  if (AUTO_INVENTORY_EXCLUDED_GROUPS.has(group)) return false;
  if (isDatedExecutionReport(relativePath)) return false;
  return true;
}

function fail(message) {
  console.error(`[docs_index] ERROR: ${message}`);
  process.exit(1);
}

function toPosix(relativePath) {
  return relativePath.split(path.sep).join('/');
}

function collectMarkdownFiles(rootDir, currentDir = rootDir, results = []) {
  const entries = fs.readdirSync(currentDir, { withFileTypes: true });
  for (const entry of entries) {
    const absolutePath = path.join(currentDir, entry.name);
    if (entry.isDirectory()) {
      collectMarkdownFiles(rootDir, absolutePath, results);
      continue;
    }
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue;
    results.push(toPosix(path.relative(rootDir, absolutePath)));
  }
  return results;
}

function extractTitle(markdown) {
  const lines = markdown.split('\n');
  for (const line of lines) {
    if (line.startsWith('# ')) {
      return line.slice(2).trim();
    }
  }
  return null;
}

function escapeTableCell(value) {
  return value.replace(/\|/g, '\\|');
}

function getGroup(relativePath) {
  if (!relativePath.includes('/')) return 'root';
  const [group] = relativePath.split('/');
  return group || 'root';
}

function compareGroup(a, b) {
  const aIndex = GROUP_ORDER.indexOf(a);
  const bIndex = GROUP_ORDER.indexOf(b);
  if (aIndex >= 0 && bIndex >= 0) return aIndex - bIndex;
  if (aIndex >= 0) return -1;
  if (bIndex >= 0) return 1;
  return a.localeCompare(b);
}

function renderInventory(filesWithTitles) {
  const groups = new Map();

  for (const row of filesWithTitles) {
    const group = getGroup(row.relativePath);
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group).push(row);
  }

  const groupNames = [...groups.keys()].sort(compareGroup);
  const lines = [];
  lines.push('## Auto-Generated Inventory');
  lines.push('');
  lines.push('This section is generated by `scripts/generate/docs_index.mjs`. Do not edit manually.');
  lines.push('');

  for (const group of groupNames) {
    const rows = groups.get(group) ?? [];
    rows.sort((a, b) => a.relativePath.localeCompare(b.relativePath));
    lines.push(`### ${group === 'root' ? '(root)' : `${group}/`}`);
    lines.push('');
    lines.push('| File | Title |');
    lines.push('|---|---|');
    for (const row of rows) {
      lines.push(
        `| [${row.relativePath}](${row.relativePath}) | ${escapeTableCell(row.title)} |`,
      );
    }
    lines.push('');
  }

  return `${lines.join('\n').trim()}\n`;
}

function replaceBlock(content, block) {
  const startIndex = content.indexOf(START_MARKER);
  const endIndex = content.indexOf(END_MARKER);
  const wrapped = `${START_MARKER}\n${block}${END_MARKER}`;

  if (startIndex >= 0 && endIndex >= 0 && endIndex > startIndex) {
    const before = content.slice(0, startIndex).replace(/\s*$/, '');
    const after = content.slice(endIndex + END_MARKER.length).replace(/^\s*/, '');
    return `${before}\n\n${wrapped}\n\n${after}`.replace(/\s+$/, '') + '\n';
  }

  const trimmed = content.replace(/\s+$/, '');
  return `${trimmed}\n\n${wrapped}\n`;
}

const scriptPath = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(scriptPath), '..', '..');
const docsRoot = path.join(repoRoot, 'docs');
const indexPath = path.join(docsRoot, 'INDEX.md');
const checkOnly = process.argv.includes('--check');

if (!fs.existsSync(docsRoot)) fail('docs directory not found');
if (!fs.existsSync(indexPath)) fail('docs/INDEX.md not found');

const markdownFiles = collectMarkdownFiles(docsRoot)
  .filter((relativePath) => !relativePath.startsWith('deprecated/'))
  .filter((relativePath) => shouldIncludeInAutoInventory(relativePath))
  .sort((a, b) => a.localeCompare(b));

if (markdownFiles.length === 0) fail('no markdown files found in docs/');

const filesWithTitles = markdownFiles.map((relativePath) => {
  const absolutePath = path.join(docsRoot, relativePath);
  const content = fs.readFileSync(absolutePath, 'utf8');
  const title = extractTitle(content) ?? path.basename(relativePath, '.md');
  return { relativePath, title };
});

const inventoryBlock = renderInventory(filesWithTitles);
const currentIndex = fs.readFileSync(indexPath, 'utf8');
const nextIndex = replaceBlock(currentIndex, inventoryBlock);

if (checkOnly) {
  if (currentIndex !== nextIndex) {
    fail('docs/INDEX.md inventory is stale. Run: npm run docs:index');
  }
  console.log('[docs_index] OK: docs/INDEX.md inventory is up to date.');
  process.exit(0);
}

fs.writeFileSync(indexPath, nextIndex, 'utf8');
console.log(`[docs_index] Updated docs/INDEX.md (${filesWithTitles.length} docs scanned)`);
