#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

function fail(message) {
  console.error(`[repo_facts] ERROR: ${message}`);
  process.exit(1);
}

function countMatches(text, pattern) {
  const matches = text.match(pattern);
  return matches ? matches.length : 0;
}

// Count MCP tool definitions in a single Rust source file.
//
// The MCP server uses two source forms for tool registration, and a
// correct count must include both:
//
//   1. The `#[tool(...)]` proc-macro attribute (and the absolute-path
//      `#[::rmcp::tool(...)]` form emitted by `mcp_tools! { raw {...} }`
//      blocks). We track paren balance to find the matching `)`, the
//      same way `scripts/generate/mcp_tools.mjs` does, so descriptions
//      with embedded `(` / `)` don't end the match early.
//   2. The `mcp_tools! { write/write_ref/read/read_ref/read_noargs ... }`
//      declarative-macro entries, which expand into `#[tool]` at compile
//      time but don't carry the literal `#[tool(` token in source. The
//      previous regex-only approach miscounted by ~109 tools (issue
//      #3350) because it only saw form (1).
//
// This logic mirrors `extractTools()` in `scripts/generate/mcp_tools.mjs`.
// Keep the two in sync.
function countMcpToolsInSource(source) {
  let count = 0;

  // Form 1: `#[tool(...)]` (and `#[::rmcp::tool(...)]`) attributes.
  const toolStartRe =
    /#\s*\[\s*(?:::\s*)?(?:[A-Za-z_][A-Za-z0-9_]*\s*::\s*)*tool\s*\(/g;
  let startMatch;
  while ((startMatch = toolStartRe.exec(source)) !== null) {
    const openPos = startMatch.index + startMatch[0].length;
    let depth = 1;
    let inString = false;
    let escaped = false;
    let i = openPos;
    while (i < source.length && depth > 0) {
      const ch = source[i];
      if (escaped) {
        escaped = false;
      } else if (ch === '\\' && inString) {
        escaped = true;
      } else if (ch === '"') {
        inString = !inString;
      } else if (!inString) {
        if (ch === '(') depth++;
        else if (ch === ')') depth--;
      }
      if (depth > 0) i++;
    }
    count++;
  }

  // Form 2: `mcp_tools! { ... }` declarative entries.
  const formRe =
    /\b(write|write_ref|read|read_ref)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\([^)]*\)\s*(?:->\s*[A-Za-z0-9_:]+\s*)?;\s*"((?:[^"\\]|\\.)*)"\s*;/gs;
  while (formRe.exec(source) !== null) {
    count++;
  }
  const noArgsRe =
    /\bread_noargs\s+([A-Za-z_][A-Za-z0-9_]*)\s*->\s*[A-Za-z0-9_:]+\s*;\s*"((?:[^"\\]|\\.)*)"\s*;/gs;
  while (noArgsRe.exec(source) !== null) {
    count++;
  }

  return count;
}

// Sanity floor: if the MCP tool count drops below this number, the
// generator fails loudly. Lorvex shipped 120 MCP tools at the time
// this floor was added (#3350); 50 is well below current truth but
// well above the broken-regex 11 the previous generator produced when
// it missed every `mcp_tools!` macro entry. This catches a future
// regression in `countMcpToolsInSource()` immediately.
const MCP_TOOL_COUNT_FLOOR = 50;

function listFiles(dirPath, predicate) {
  return fs
    .readdirSync(dirPath, { withFileTypes: true })
    .filter((entry) => entry.isFile() && predicate(entry.name))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
}

function listFilesRecursive(dirPath, predicate) {
  const results = [];

  function walk(currentDir) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const absolutePath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        walk(absolutePath);
        continue;
      }
      if (entry.isFile() && predicate(entry.name, absolutePath)) {
        results.push(absolutePath);
      }
    }
  }

  walk(dirPath);
  return results.sort((a, b) => a.localeCompare(b));
}

function toPosix(relativePath) {
  return relativePath.split(path.sep).join('/');
}

function compareByMigrationVersion(a, b) {
  const aMatch = a.match(/^(\d+)_/);
  const bMatch = b.match(/^(\d+)_/);
  const aVersion = aMatch ? Number(aMatch[1]) : -1;
  const bVersion = bMatch ? Number(bMatch[1]) : -1;
  if (aVersion !== bVersion) {
    return aVersion - bVersion;
  }
  return a.localeCompare(b);
}

function renderFactsMarkdown({
  totalMcpTools,
  toolFileCount,
  toolCounts,
  migrationFiles,
  latestMigration,
  rustIpcCommandCount,
  rustIpcCommandFileCount,
  localeFileCount,
  localeCoverage,
}) {
  const lines = [];

  lines.push('# Repository Facts (Generated)');
  lines.push('');
  lines.push('This file is generated by `scripts/generate/repo_facts.mjs`. Do not edit manually.');
  lines.push('');
  lines.push('Regenerate: `npm run docs:repo-facts`');
  lines.push('');
  lines.push('Verify freshness: `npm run verify:repo-facts`');
  lines.push('');
  lines.push('## MCP Tool Inventory');
  lines.push('');
  lines.push(`- Total MCP tools: **${totalMcpTools}**`);
  lines.push(`- Rust source files with tool definitions: **${toolFileCount}**`);
  lines.push('');
  lines.push('| Rust source file | Tool definitions |');
  lines.push('|---|---:|');
  for (const row of toolCounts) {
    lines.push(`| \`${row.path}\` | ${row.count} |`);
  }
  lines.push('');
  lines.push('## Database Migrations');
  lines.push('');
  lines.push(`- Total migration files: **${migrationFiles.length}**`);
  lines.push(`- Latest migration: \`${latestMigration}\``);
  lines.push('');
  lines.push('| Migration file |');
  lines.push('|---|');
  for (const fileName of migrationFiles) {
    lines.push(`| \`lorvex-store/src/schema/${fileName}\` |`);
  }
  lines.push('');
  lines.push('## Additional Stable Facts');
  lines.push('');
  lines.push(`- Rust IPC commands (\`app/src-tauri/src/**/*.rs\`): **${rustIpcCommandCount}** across **${rustIpcCommandFileCount}** file(s)`);
  lines.push(`- Locale files (\`app/src/locales/*.json\`, excluding \`_invariant.json\`): **${localeFileCount}**`);
  lines.push('');
  lines.push('## Locale coverage');
  lines.push('');
  lines.push(
    `Per-locale completion against \`en.json\` (${localeCoverage.totalKeys} keys, including invariant keys spread at runtime).`,
  );
  lines.push(
    `Strict-parity locales from \`app/src/locales/strict-parity.json\` (${localeCoverage.strictLocaleCodes.join(', ')}) are first-class and parity-gated by \`npm run verify:i18n\`; other locales fall back to English at runtime — see \`docs/design/COPY_GUIDELINES.md\` "Localization Policy".`,
  );
  lines.push('');
  lines.push('| Locale | Translated | Missing | Coverage |');
  lines.push('|---|---:|---:|---:|');
  for (const row of localeCoverage.rows) {
    const pct = `${(row.coverage * 100).toFixed(1)}%`;
    lines.push(`| \`${row.code}\` | ${row.translated} | ${row.missing} | ${pct} |`);
  }

  return `${lines.join('\n')}\n`;
}

function computeLocaleCoverage(localesDir) {
  const enPath = path.join(localesDir, 'en.json');
  const invariantPath = path.join(localesDir, '_invariant.json');
  const strictParityPath = path.join(localesDir, 'strict-parity.json');
  if (!fs.existsSync(enPath)) {
    fail(`Missing en.json at: ${enPath}`);
  }
  if (!fs.existsSync(strictParityPath)) {
    fail(`Missing strict parity locale config at: ${strictParityPath}`);
  }
  const readKeys = (filePath) =>
    new Set(Object.keys(JSON.parse(fs.readFileSync(filePath, 'utf8'))));
  const strictLocaleCodes = JSON.parse(fs.readFileSync(strictParityPath, 'utf8'));
  if (!Array.isArray(strictLocaleCodes) || strictLocaleCodes.some((code) => typeof code !== 'string')) {
    fail('strict-parity.json must be a JSON array of locale codes');
  }
  const enKeys = readKeys(enPath);
  const invariantKeys = fs.existsSync(invariantPath) ? readKeys(invariantPath) : new Set();
  // INVARIANT keys are spread into every locale at runtime by
  // `registry.ts`, so they count as auto-translated for every locale —
  // including `en` itself, which doesn't redeclare them.
  for (const k of invariantKeys) enKeys.add(k);
  const enKeyArray = Array.from(enKeys);
  const totalKeys = enKeys.size;

  const localeFiles = listFiles(
    localesDir,
    (name) => name.endsWith('.json') && !name.startsWith('_') && name !== 'strict-parity.json',
  );
  const rows = [];
  for (const fileName of localeFiles) {
    const code = fileName.replace(/\.json$/, '');
    const keys = readKeys(path.join(localesDir, fileName));
    for (const k of invariantKeys) keys.add(k);
    const translated = enKeyArray.filter((key) => keys.has(key)).length;
    const coverage = totalKeys === 0 ? 1 : translated / totalKeys;
    rows.push({
      code,
      translated,
      missing: totalKeys - translated,
      coverage,
    });
  }
  rows.sort((a, b) => {
    if (a.code === 'en') return -1;
    if (b.code === 'en') return 1;
    if (b.coverage !== a.coverage) return b.coverage - a.coverage;
    return a.code.localeCompare(b.code);
  });
  return { totalKeys, strictLocaleCodes, rows };
}

const scriptPath = fileURLToPath(import.meta.url);
const scriptDir = path.dirname(scriptPath);
const repoRoot = path.resolve(scriptDir, '..', '..');
const outputPath = path.join(repoRoot, 'docs', 'reference', 'REPO_FACTS.md');
const checkOnly = process.argv.includes('--check');

const mcpRuntimeDir = path.join(repoRoot, 'mcp-server', 'src');
const migrationsDir = path.join(repoRoot, 'lorvex-store', 'src', 'schema');
const rustCommandSourceDir = path.join(repoRoot, 'app', 'src-tauri', 'src');
const localesDir = path.join(repoRoot, 'app', 'src', 'locales');

if (!fs.existsSync(mcpRuntimeDir)) {
  fail(`MCP runtime source directory not found: ${mcpRuntimeDir}`);
}
if (!fs.existsSync(migrationsDir)) {
  fail(`Migrations directory not found: ${migrationsDir}`);
}
if (!fs.existsSync(rustCommandSourceDir)) {
  fail(`Rust Tauri source directory not found: ${rustCommandSourceDir}`);
}
if (!fs.existsSync(localesDir)) {
  fail(`Locales directory not found: ${localesDir}`);
}

// Mirror SKIP_DIRS from `scripts/generate/mcp_tools.mjs`: these
// top-level subdirectories never contain tool routers. In particular,
// `server/` houses the `mcp_tools!` macro *definition*, whose body
// contains literal `#[::rmcp::tool(...)]` tokens that would otherwise
// be miscounted as real tool registrations.
const MCP_SKIP_DIRS = new Set(['db', 'error', 'shutdown', 'server']);
const toolFiles = listFilesRecursive(mcpRuntimeDir, (name, absolutePath) => {
  if (!name.endsWith('.rs')) return false;
  const rel = path.relative(mcpRuntimeDir, absolutePath);
  const topSegment = rel.split(path.sep)[0];
  if (rel.includes(path.sep) && MCP_SKIP_DIRS.has(topSegment)) return false;
  return true;
});
if (toolFiles.length === 0) {
  fail(`No MCP Rust source files found in: ${toPosix(path.relative(repoRoot, mcpRuntimeDir))}`);
}

// Only count tool definitions in router source files. This matches
// the canonical extractor in `scripts/generate/mcp_tools.mjs`: post-
// #3370 every router lives at `<domain>/router.rs` (or under
// `workflow/router/<topic>.rs`), so we identify routers by the
// presence of either a `#[tool_router(...)]` attribute or a
// `mcp_tools! { ... }` invocation. Without this filter, the literal
// `#[::rmcp::tool(...)]` tokens inside the `mcp_tools!` macro
// *definition* (not its call sites) get counted as real tools,
// inflating the total.
function isRouterFile(_absolutePath, source) {
  if (/#\s*\[\s*(?:::\s*)?(?:[A-Za-z_][A-Za-z0-9_]*\s*::\s*)*tool_router\s*\(/.test(source)) {
    return true;
  }
  if (/\bmcp_tools!\s*\{/.test(source)) return true;
  return false;
}

const toolCounts = toolFiles
  .map((absolutePath) => {
    const source = fs.readFileSync(absolutePath, 'utf8');
    if (!isRouterFile(absolutePath, source)) {
      return { path: toPosix(path.relative(repoRoot, absolutePath)), count: 0 };
    }
    const count = countMcpToolsInSource(source);
    return {
      path: toPosix(path.relative(repoRoot, absolutePath)),
      count,
    };
  })
  .filter((row) => row.count > 0)
  .sort((a, b) => a.path.localeCompare(b.path));

if (toolCounts.length === 0) {
  fail('No Rust MCP tool definitions found in mcp-server/src/*.rs');
}

const totalMcpTools = toolCounts.reduce((sum, row) => sum + row.count, 0);
const toolFileCount = toolCounts.length;

if (totalMcpTools < MCP_TOOL_COUNT_FLOOR) {
  fail(
    `MCP tool count (${totalMcpTools}) is below sanity floor (${MCP_TOOL_COUNT_FLOOR}). ` +
      `This usually means the parser missed a tool registration form — ` +
      `see scripts/generate/mcp_tools.mjs for the canonical extractor.`,
  );
}

const migrationFiles = listFiles(migrationsDir, (name) => name.endsWith('.sql')).sort(compareByMigrationVersion);
if (migrationFiles.length === 0) {
  fail(`No SQL migration files found in: ${migrationsDir}`);
}
const latestMigration = migrationFiles[migrationFiles.length - 1];

const rustCommandFiles = listFilesRecursive(
  rustCommandSourceDir,
  (name) => name.endsWith('.rs'),
);
const rustCommandCounts = rustCommandFiles
  .map((absolutePath) => {
    const source = fs.readFileSync(absolutePath, 'utf8');
    // Count #[tauri::command] only on non-comment lines
    const lines = source.split('\n');
    let count = 0;
    for (const line of lines) {
      const trimmed = line.trimStart();
      if (trimmed.startsWith('//') || trimmed.startsWith('///')) continue;
      if (/#\s*\[\s*tauri::command\s*\]/.test(line)) count++;
    }
    return count;
  })
  .filter((count) => count > 0);
const rustIpcCommandCount = rustCommandCounts.reduce((sum, count) => sum + count, 0);
const rustIpcCommandFileCount = rustCommandCounts.length;
if (rustIpcCommandCount === 0) {
  fail(`No #[tauri::command] functions found in: ${toPosix(path.relative(repoRoot, rustCommandSourceDir))}`);
}

// Per-language translation tables now live as `<code>.json`. The
// shared `_invariant.json` (cross-locale-shared keys) is excluded —
// it isn't itself a per-language table. The `index.ts` / `registry.ts`
// / `runtime.ts` / `types.generated.ts` files are the runtime resolver
// layer and live alongside the JSON catalogs.
const localeFileCount = listFiles(
  localesDir,
  (name) => name.endsWith('.json') && name !== '_invariant.json' && name !== 'strict-parity.json',
).length;
if (localeFileCount === 0) {
  fail(`No locale files found in: ${localesDir}`);
}

const localeCoverage = computeLocaleCoverage(localesDir);

const nextContent = renderFactsMarkdown({
  totalMcpTools,
  toolFileCount,
  toolCounts,
  migrationFiles,
  latestMigration,
  rustIpcCommandCount,
  rustIpcCommandFileCount,
  localeFileCount,
  localeCoverage,
});

if (checkOnly) {
  if (!fs.existsSync(outputPath)) {
    fail(`Facts file missing: ${toPosix(path.relative(repoRoot, outputPath))}`);
  }
  const currentContent = fs.readFileSync(outputPath, 'utf8');
  if (currentContent !== nextContent) {
    fail(
      `Stale facts file: ${toPosix(path.relative(repoRoot, outputPath))}. Run: npm run docs:repo-facts`,
    );
  }
  console.log('[repo_facts] OK: docs/reference/REPO_FACTS.md is up to date.');
  process.exit(0);
}

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, nextContent, 'utf8');

console.log('[repo_facts] Wrote docs/reference/REPO_FACTS.md');
console.log(`[repo_facts] MCP tools: ${totalMcpTools} across ${toolFileCount} files`);
console.log(`[repo_facts] Migrations: ${migrationFiles.length} files (latest ${latestMigration})`);
console.log(
  `[repo_facts] Rust IPC commands: ${rustIpcCommandCount} across ${rustIpcCommandFileCount} files`,
);
console.log(`[repo_facts] Locale files: ${localeFileCount}`);
