#!/usr/bin/env node
/**
 * Locale coverage reporter.
 *
 * Renders a per-locale translation coverage table against the master
 * `en.json` catalog. Companion to `i18n_parity.mjs`: parity gates the
 * build, this prints a snapshot operators can read at a glance to see
 * which locales are due for translation work.
 *
 * Usage:
 *   node scripts/verify/locale_coverage.mjs            # human-readable table
 *   node scripts/verify/locale_coverage.mjs --json     # machine-readable JSON
 *   node scripts/verify/locale_coverage.mjs --format=md  # Markdown table
 *
 * Exit code is always 0 — this is a report, not a gate. Use
 * `npm run verify:i18n` for the hard parity check.
 */

import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const localesDir = path.join(root, 'app/src/locales');
const EN_FILE = 'en.json';
const INVARIANT_FILE = path.join(localesDir, '_invariant.json');

function readJsonKeys(absPath) {
  const data = JSON.parse(fs.readFileSync(absPath, 'utf8'));
  return new Set(Object.keys(data));
}

function parseFormatFlag(argv) {
  for (const arg of argv.slice(2)) {
    if (arg === '--json') return 'json';
    if (arg === '--md' || arg === '--format=md' || arg === '--format=markdown') return 'md';
    if (arg === '--text' || arg === '--format=text') return 'text';
  }
  return 'text';
}

function buildRows() {
  if (!fs.existsSync(localesDir)) {
    console.error(`ERROR: locales dir not found: ${localesDir}`);
    process.exit(1);
  }
  const enKeys = readJsonKeys(path.join(localesDir, EN_FILE));
  // _invariant.json keys are spread into every locale at runtime by
  // registry.ts; treat them as auto-translated for coverage reporting.
  const invariantKeys = fs.existsSync(INVARIANT_FILE) ? readJsonKeys(INVARIANT_FILE) : new Set();
  for (const k of invariantKeys) enKeys.add(k);
  if (enKeys.size === 0) {
    console.error('ERROR: no translation keys found in en.json');
    process.exit(1);
  }
  const enKeyArray = Array.from(enKeys);

  const localeFiles = fs
    .readdirSync(localesDir)
    .filter((file) => file.endsWith('.json') && !file.startsWith('_'))
    .sort();

  const rows = [];
  for (const file of localeFiles) {
    const code = file.replace(/\.json$/, '');
    const keys = readJsonKeys(path.join(localesDir, file));
    // INVARIANT keys are spread at runtime — count them as translated.
    for (const k of invariantKeys) keys.add(k);
    const translated = enKeyArray.filter((key) => keys.has(key)).length;
    const extra = Array.from(keys).filter((key) => !enKeys.has(key)).length;
    const coverage = translated / enKeys.size;
    rows.push({
      code,
      translated,
      total: enKeys.size,
      missing: enKeys.size - translated,
      extra,
      coverage,
    });
  }

  rows.sort((a, b) => {
    if (a.code === 'en') return -1;
    if (b.code === 'en') return 1;
    if (b.coverage !== a.coverage) return b.coverage - a.coverage;
    return a.code.localeCompare(b.code);
  });

  return { rows, totalKeys: enKeys.size };
}

function renderText(rows, totalKeys) {
  const codeWidth = Math.max(6, ...rows.map((r) => r.code.length));
  const header =
    `  ${'locale'.padEnd(codeWidth)}  ${'translated'.padStart(10)}  ` +
    `${'missing'.padStart(7)}  ${'extra'.padStart(5)}  coverage`;
  const lines = [
    `Locale coverage against en.json (${totalKeys} keys)`,
    ''.padEnd(header.length, '-'),
    header,
    ''.padEnd(header.length, '-'),
  ];
  for (const row of rows) {
    const pct = (row.coverage * 100).toFixed(1).padStart(5);
    lines.push(
      `  ${row.code.padEnd(codeWidth)}  ${String(row.translated).padStart(10)}  ` +
        `${String(row.missing).padStart(7)}  ${String(row.extra).padStart(5)}  ${pct}%`,
    );
  }
  return lines.join('\n');
}

function renderMarkdown(rows, totalKeys) {
  const lines = [
    `# Locale coverage`,
    '',
    `Coverage against \`en.json\` (${totalKeys} keys). Generated by \`scripts/verify/locale_coverage.mjs\`.`,
    '',
    '| Locale | Translated | Missing | Extra | Coverage |',
    '| --- | ---: | ---: | ---: | ---: |',
  ];
  for (const row of rows) {
    const pct = `${(row.coverage * 100).toFixed(1)}%`;
    lines.push(
      `| \`${row.code}\` | ${row.translated} | ${row.missing} | ${row.extra} | ${pct} |`,
    );
  }
  return lines.join('\n');
}

function renderJson(rows, totalKeys) {
  return JSON.stringify(
    {
      total_keys: totalKeys,
      locales: rows.map((row) => ({
        code: row.code,
        translated: row.translated,
        missing: row.missing,
        extra: row.extra,
        coverage_ratio: row.coverage,
      })),
    },
    null,
    2,
  );
}

const format = parseFormatFlag(process.argv);
const { rows, totalKeys } = buildRows();
let output;
switch (format) {
  case 'json':
    output = renderJson(rows, totalKeys);
    break;
  case 'md':
    output = renderMarkdown(rows, totalKeys);
    break;
  default:
    output = renderText(rows, totalKeys);
}
console.log(output);
