import AppIntents
import Foundation
import LorvexCore
import LorvexSystemIntents
import Testing
import UniformTypeIdentifiers

@testable import LorvexApple
@testable import LorvexSystemIntents

@Test
func taskLifecycleIntentsAreDefaultConstructible() {
  _ = ReadLorvexTaskIntent()
  _ = ListLorvexTasksIntent()
  _ = SearchLorvexTasksIntent()
  _ = ReadLorvexDeferredTasksIntent()
  _ = ReadLorvexUpcomingTasksIntent()
  _ = ReadLorvexDependencyGraphIntent()
  _ = CompleteLorvexTaskIntent()
  _ = UpdateLorvexTaskIntent()
  _ = CancelLorvexTaskIntent()
  _ = ReopenLorvexTaskIntent()
  _ = DeferLorvexTaskIntent()
  _ = AppendLorvexTaskBodyIntent()
  _ = SetLorvexTaskRemindersIntent()
  _ = SetLorvexTaskRecurrenceIntent()
  _ = RemoveLorvexTaskRecurrenceIntent()
  _ = AddLorvexTaskRecurrenceExceptionIntent()
  _ = RemoveLorvexTaskRecurrenceExceptionIntent()
  _ = AddLorvexChecklistItemIntent()
  _ = ToggleLorvexChecklistItemIntent()
  _ = UpdateLorvexChecklistItemIntent()
  _ = RemoveLorvexChecklistItemIntent()
  _ = BatchCreateLorvexTasksIntent()
  _ = BatchCompleteLorvexTasksIntent()
  _ = BatchReopenLorvexTasksIntent()
  _ = BatchDeferLorvexTasksIntent()
  _ = BatchMoveLorvexTasksIntent()
  _ = AddLorvexTaskReminderIntent()
  _ = RemoveLorvexTaskReminderIntent()
  _ = ReadLorvexDueTaskRemindersIntent()
  _ = ReadLorvexUpcomingTaskRemindersIntent()
  #expect(ReadLorvexTaskIntent.openAppWhenRun == false)
  #expect(ListLorvexTasksIntent.openAppWhenRun == false)
  #expect(SearchLorvexTasksIntent.openAppWhenRun == false)
  #expect(ReadLorvexDeferredTasksIntent.openAppWhenRun == false)
  #expect(ReadLorvexUpcomingTasksIntent.openAppWhenRun == false)
  #expect(ReadLorvexDependencyGraphIntent.openAppWhenRun == false)
  #expect(CompleteLorvexTaskIntent.openAppWhenRun == false)
  #expect(UpdateLorvexTaskIntent.openAppWhenRun == false)
  #expect(CancelLorvexTaskIntent.openAppWhenRun == false)
  #expect(ReopenLorvexTaskIntent.openAppWhenRun == false)
  #expect(DeferLorvexTaskIntent.openAppWhenRun == false)
  #expect(AppendLorvexTaskBodyIntent.openAppWhenRun == false)
  #expect(SetLorvexTaskRemindersIntent.openAppWhenRun == false)
  #expect(SetLorvexTaskRecurrenceIntent.openAppWhenRun == false)
  #expect(RemoveLorvexTaskRecurrenceIntent.openAppWhenRun == false)
  #expect(AddLorvexTaskRecurrenceExceptionIntent.openAppWhenRun == false)
  #expect(RemoveLorvexTaskRecurrenceExceptionIntent.openAppWhenRun == false)
  #expect(AddLorvexChecklistItemIntent.openAppWhenRun == false)
  #expect(ToggleLorvexChecklistItemIntent.openAppWhenRun == false)
  #expect(UpdateLorvexChecklistItemIntent.openAppWhenRun == false)
  #expect(RemoveLorvexChecklistItemIntent.openAppWhenRun == false)
  #expect(BatchCreateLorvexTasksIntent.openAppWhenRun == false)
  #expect(BatchCompleteLorvexTasksIntent.openAppWhenRun == false)
  #expect(BatchReopenLorvexTasksIntent.openAppWhenRun == false)
  #expect(BatchDeferLorvexTasksIntent.openAppWhenRun == false)
  #expect(BatchMoveLorvexTasksIntent.openAppWhenRun == false)
  #expect(AddLorvexTaskReminderIntent.openAppWhenRun == false)
  #expect(RemoveLorvexTaskReminderIntent.openAppWhenRun == false)
  #expect(ReadLorvexDueTaskRemindersIntent.openAppWhenRun == false)
  #expect(ReadLorvexUpcomingTaskRemindersIntent.openAppWhenRun == false)
}

// MARK: - Content and memory intents

@Test
func createListHabitAndCalendarEventIntentsAreDefaultConstructible() {
  _ = CreateLorvexListIntent()
  _ = UpdateLorvexListIntent()
  _ = DeleteLorvexListIntent()
  _ = ReadLorvexListsIntent()
  _ = ReadLorvexListDetailIntent()
  _ = ReadLorvexListHealthIntent()
  _ = ListLorvexTagsIntent()
  _ = RenameLorvexTagIntent()
  _ = FindLorvexTasksByTagIntent()
  _ = CreateLorvexHabitIntent()
  _ = UpdateLorvexHabitIntent()
  _ = DeleteLorvexHabitIntent()
  _ = CreateLorvexCalendarEventIntent()
  _ = UpdateLorvexCalendarEventIntent()
  _ = DeleteLorvexCalendarEventIntent()
  _ = ReadLorvexCalendarTimelineIntent()
  _ = SearchLorvexCalendarEventsIntent()
  _ = LinkLorvexTaskToProviderEventIntent()
  _ = UnlinkLorvexTaskFromProviderEventIntent()
  _ = ReadLorvexLinkedEventsForTaskIntent()
  _ = ReadLorvexLinkedTasksForEventIntent()
  #expect(CreateLorvexListIntent.openAppWhenRun == false)
  #expect(UpdateLorvexListIntent.openAppWhenRun == false)
  #expect(DeleteLorvexListIntent.openAppWhenRun == false)
  #expect(ReadLorvexListsIntent.openAppWhenRun == false)
  #expect(ReadLorvexListDetailIntent.openAppWhenRun == false)
  #expect(ReadLorvexListHealthIntent.openAppWhenRun == false)
  #expect(ListLorvexTagsIntent.openAppWhenRun == false)
  #expect(RenameLorvexTagIntent.openAppWhenRun == false)
  #expect(FindLorvexTasksByTagIntent.openAppWhenRun == false)
  #expect(CreateLorvexHabitIntent.openAppWhenRun == false)
  #expect(UpdateLorvexHabitIntent.openAppWhenRun == false)
  #expect(DeleteLorvexHabitIntent.openAppWhenRun == false)
  #expect(CreateLorvexCalendarEventIntent.openAppWhenRun == false)
  #expect(UpdateLorvexCalendarEventIntent.openAppWhenRun == false)
  #expect(DeleteLorvexCalendarEventIntent.openAppWhenRun == false)
  #expect(ReadLorvexCalendarTimelineIntent.openAppWhenRun == false)
  #expect(SearchLorvexCalendarEventsIntent.openAppWhenRun == false)
  #expect(LinkLorvexTaskToProviderEventIntent.openAppWhenRun == false)
  #expect(UnlinkLorvexTaskFromProviderEventIntent.openAppWhenRun == false)
  #expect(ReadLorvexLinkedEventsForTaskIntent.openAppWhenRun == false)
  #expect(ReadLorvexLinkedTasksForEventIntent.openAppWhenRun == false)
}

@Test
func completeAndResetHabitIntentsAreDefaultConstructible() {
  _ = CompleteLorvexHabitIntent()
  _ = ResetLorvexHabitIntent()
  _ = ReadLorvexHabitCompletionsIntent()
  _ = ReadLorvexHabitStatsIntent()
  _ = BatchCompleteLorvexHabitsIntent()
  _ = ReadLorvexHabitReminderPoliciesIntent()
  _ = UpsertLorvexHabitReminderPolicyIntent()
  #expect(CompleteLorvexHabitIntent.openAppWhenRun == false)
  #expect(ResetLorvexHabitIntent.openAppWhenRun == false)
  #expect(ReadLorvexHabitCompletionsIntent.openAppWhenRun == false)
  #expect(ReadLorvexHabitStatsIntent.openAppWhenRun == false)
  #expect(BatchCompleteLorvexHabitsIntent.openAppWhenRun == false)
  #expect(ReadLorvexHabitReminderPoliciesIntent.openAppWhenRun == false)
  #expect(UpsertLorvexHabitReminderPolicyIntent.openAppWhenRun == false)
}

@Test
func diagnosticsIntentsAreDefaultConstructible() {
  _ = ReadLorvexPreferencesIntent()
  _ = ReadLorvexPreferenceIntent()
  _ = SetLorvexPreferenceIntent()
  _ = DeleteLorvexPreferenceIntent()
  _ = CompleteLorvexSetupIntent()
  _ = ReadLorvexOverviewIntent()
  _ = ReadLorvexSessionContextIntent()
  _ = ExportLorvexDataIntent()
  _ = ExportLorvexCalendarICSIntent()
  _ = ReadLorvexRuntimeDiagnosticsIntent()
  _ = ReadLorvexSetupStatusIntent()
  _ = ReadLorvexSyncStatusIntent()
  _ = ReadLorvexAIChangelogIntent()
  _ = ReadLorvexRecentLogsIntent()
  _ = ReadLorvexGuideIntent()
  #expect(ReadLorvexPreferencesIntent.openAppWhenRun == false)
  #expect(ReadLorvexPreferenceIntent.openAppWhenRun == false)
  #expect(SetLorvexPreferenceIntent.openAppWhenRun == false)
  #expect(DeleteLorvexPreferenceIntent.openAppWhenRun == false)
  #expect(CompleteLorvexSetupIntent.openAppWhenRun == false)
  #expect(ReadLorvexOverviewIntent.openAppWhenRun == false)
  #expect(ReadLorvexSessionContextIntent.openAppWhenRun == false)
  #expect(ExportLorvexDataIntent.openAppWhenRun == false)
  #expect(ExportLorvexCalendarICSIntent.openAppWhenRun == false)
  #expect(ReadLorvexRuntimeDiagnosticsIntent.openAppWhenRun == false)
  #expect(ReadLorvexSetupStatusIntent.openAppWhenRun == false)
  #expect(ReadLorvexSyncStatusIntent.openAppWhenRun == false)
  #expect(ReadLorvexAIChangelogIntent.openAppWhenRun == false)
  #expect(ReadLorvexRecentLogsIntent.openAppWhenRun == false)
  #expect(ReadLorvexGuideIntent.openAppWhenRun == false)
}

@Test
func reviewIntentsAreDefaultConstructible() {
  _ = SaveLorvexDailyReviewIntent()
  _ = AmendLorvexDailyReviewIntent()
  _ = ReadLorvexReviewHistoryIntent()
  _ = ReadLorvexWeeklyReviewIntent()
  #expect(SaveLorvexDailyReviewIntent.openAppWhenRun == false)
  #expect(AmendLorvexDailyReviewIntent.openAppWhenRun == false)
  #expect(ReadLorvexReviewHistoryIntent.openAppWhenRun == false)
  #expect(ReadLorvexWeeklyReviewIntent.openAppWhenRun == false)
}

@Test
func contentAndMemoryIntentsAreDefaultConstructible() {
  _ = SaveLorvexMemoryIntent()
  _ = ReadLorvexMemoryIntent()
  _ = DeleteLorvexMemoryIntent()
  #expect(SaveLorvexMemoryIntent.openAppWhenRun == false)
  #expect(ReadLorvexMemoryIntent.openAppWhenRun == false)
  #expect(DeleteLorvexMemoryIntent.openAppWhenRun == false)
}
