import Foundation

/// Loads the bundled third-party notices document shipped with the app.
///
/// The text is generated by `script/generate_acknowledgments.py` from the
/// resolved SwiftPM dependency graph (`Package.resolved`) and each
/// dependency's own LICENSE/NOTICE file; `script/verify_acknowledgments.py`
/// fails the build if a dependency add, removal, or version bump is not
/// reflected in the bundled text, so the string returned here always covers
/// exactly the packages linked into the shipping app.
public enum ThirdPartyAcknowledgments {
  /// Anchor for `Bundle(for:)` so the resource resolves from the bundle
  /// carrying this module's code.
  private final class ResourceAnchor {}

  private static func resourceBundle() -> Bundle {
    #if SWIFT_PACKAGE
      LorvexResourceBundleResolver.bundle(
        named: "LorvexApple_LorvexCore.bundle",
        bundleFor: ResourceAnchor.self,
        swiftPMBundle: Bundle.module)
    #else
      Bundle(for: ResourceAnchor.self)
    #endif
  }

  /// The full acknowledgments text. Falls back to the in-repo source file
  /// (mirroring the schema/checksums dev fallback) when no packaged resource
  /// bundle is found, and to a short explanatory placeholder — never a crash —
  /// if neither is available.
  public static var text: String {
    let resolved = resourceBundle()
    for bundle in [resolved, Bundle(for: ResourceAnchor.self), Bundle.main] {
      if let url = bundle.url(forResource: "ACKNOWLEDGMENTS", withExtension: "md"),
        let contents = try? String(contentsOf: url, encoding: .utf8)
      {
        return contents
      }
    }
    let devPath = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()  // Support
      .deletingLastPathComponent()  // LorvexCore
      .appendingPathComponent("Resources/ACKNOWLEDGMENTS.md")
    if let contents = try? String(contentsOf: devPath, encoding: .utf8) {
      return contents
    }
    return "Third-party acknowledgments are unavailable in this build."
  }
}
