//! Workflow tool router.
//!
//! The workflow router aggregates the assistant-facing workflow surfaces —
//! focus plans, daily/weekly reviews, persistent AI memory, habit
//! tracking + reminders, diagnostic log access, plus two cross-cutting tools
//! (bulk tag rename, session context bootstrap).
//!
//! Per the rmcp `#[tool_router]` macro contract, every `#[tool]` annotation
//! must live inside one `#[tool_router]`-annotated `impl` block — that block
//! generates a `Self::<router>()` function returning a `ToolRouter<Self>`
//! built from `with_route(...)` for each tool in the block. Multiple such
//! blocks can be combined with `+`, so we split the workflow surface by
//! domain into per-submodule `#[tool_router]` impl blocks and aggregate them
//! here into the canonical `workflow_tool_router()` consumed by `server.rs`.
//!
//! Submodule layout:
//! - `focus`: set/get/add/clear/remove current focus + propose & save & read
//!   focus schedule.
//! - `daily_review`: add/amend/get a single day plus history.
//! - `weekly_review`: bounded brief and snapshot.
//! - `memory`: read/write/delete/history/restore persistent AI memory.
//! - `habit_tracking`: create/update/delete habits and complete/uncomplete +
//!   batch + read computed stats.
//! - `habit_reminders`: habit reminder policy CRUD.
//! - `logs`: ai_changelog + cross-source recent logs + feedback.
//! - `session_and_tags`: `rename_tag` and `get_session_context`.

mod daily_review;
mod focus;
mod habit_reminders;
mod habit_tracking;
mod logs;
mod memory;
mod session_and_tags;
mod weekly_review;

use crate::server::LorvexMcpServer;
use rmcp::handler::server::router::tool::ToolRouter;

impl LorvexMcpServer {
    /// Aggregate every workflow-domain sub-router into the single router
    /// consumed by `LorvexMcpServer::new`. Each sub-router is generated by
    /// an `#[tool_router]` macro on a per-domain `impl` block in the
    /// matching submodule below.
    pub(crate) fn workflow_tool_router() -> ToolRouter<Self> {
        Self::workflow_focus_tool_router()
            + Self::workflow_daily_review_tool_router()
            + Self::workflow_weekly_review_tool_router()
            + Self::workflow_memory_tool_router()
            + Self::workflow_habit_tracking_tool_router()
            + Self::workflow_habit_reminders_tool_router()
            + Self::workflow_logs_tool_router()
            + Self::workflow_session_and_tags_tool_router()
    }
}
