//! Lightweight Rust-side translations for native menu / tray labels.
//!
//! These are needed because the system tray and app menu are built before the
//! React frontend loads. We read the `language` user-preference from SQLite and
//! look up a compact translation table. Missing locales fall back to English.
//!
//! The key allowlist and lookup table are generated by `app/src-tauri/build.rs`
//! from `app/src/locales/registry.ts` and the canonical JSON catalogs. Only
//! locales with a complete `menu.*` namespace are emitted; partial locales fall
//! back to English as a whole so the native surface never mixes languages.

use crate::db;
use crate::error::AppError;
use rusqlite::{Connection, OptionalExtension};

const MENU_I18N_LOG_SOURCE: &str = "menu.i18n";

fn append_menu_i18n_log_with_conn(
    conn: &Connection,
    level: &str,
    message: &str,
    details: Option<String>,
) -> Result<(), String> {
    crate::commands::diagnostics::append_diagnostic_log_with_conn(
        conn,
        MENU_I18N_LOG_SOURCE,
        level,
        message,
        details,
    )
}

fn append_menu_i18n_log(level: &str, message: &str, details: Option<String>) {
    let Ok(conn) = db::get_conn() else {
        return;
    };
    let _ = append_menu_i18n_log_with_conn(&conn, level, message, details);
}

/// Menu string identifiers for tray and app menu items.
#[derive(Clone, Copy)]
pub enum MenuKey {
    // Top-level app menu labels
    AppMenu,
    FileMenu,
    EditMenu,
    ViewMenu,
    WindowMenu,
    HelpMenu,
    // Tray menu
    Open,
    QuickCapture,
    Quit,
    // App menu
    CheckForUpdates,
    Settings,
    // File menu
    NewTask,
    ExportData,
    ImportData,
    // Edit menu
    Find,
    // View menu
    Today,
    Next7Days,
    AllTasks,
    AiActivity,
    Calendar,
    EisenhowerMatrix,
    KanbanBoard,
    Someday,
    AiMemory,
    WeeklyReview,
    DailyReview,
    FocusMode,
    Habits,
    Dependencies,
    Recurring,
    // Window menu
    AlwaysOnTop,
    // Help menu
    Help,
    GettingStarted,
    AssistantMcpSetup,
    KeyboardShortcuts,
    ReportIssue,
}

include!(concat!(env!("OUT_DIR"), "/menu_i18n.generated.rs"));

fn parse_preferred_locale(raw: &str) -> Option<String> {
    let parsed = lorvex_domain::parse_json_string_preference(Some(raw))?;
    if KNOWN_LOCALES.iter().any(|known| *known == parsed) {
        Some(parsed)
    } else {
        None
    }
}

fn preferred_locale_from_conn(conn: &Connection) -> Result<Option<String>, String> {
    let raw = conn
        .query_row(
            "SELECT value FROM preferences WHERE key = ?1",
            rusqlite::params![lorvex_domain::preference_keys::PREF_LANGUAGE],
            |row| row.get::<_, String>(0),
        )
        .optional()
        .map_err(AppError::from)
        .map_err(String::from)?;

    match raw {
        Some(value) => parse_preferred_locale(&value)
            .map(Some)
            .ok_or_else(|| "language preference must be a JSON string".to_string()),
        None => Ok(None),
    }
}

/// Read the stored language preference from the preferences table.
/// Returns a locale code like "en", "zh", "ja", etc. Falls back to "en".
pub fn preferred_locale() -> String {
    let pool = match db::get_db() {
        Ok(pool) => pool,
        Err(error) => {
            append_menu_i18n_log(
                "warn",
                "language preference pool unavailable; falling back to English",
                Some(format!("error={error}")),
            );
            return "en".to_string();
        }
    };
    let conn = match pool.read_lock_result() {
        Ok(conn) => conn,
        Err(error) => {
            append_menu_i18n_log(
                "warn",
                "language preference read failed; falling back to English",
                Some(format!("error={error}")),
            );
            return "en".to_string();
        }
    };
    let locale_result = preferred_locale_from_conn(&conn);
    drop(conn);
    match locale_result {
        Ok(Some(locale)) => locale,
        Ok(None) => "en".to_string(),
        Err(error) => {
            append_menu_i18n_log(
                "warn",
                "language preference invalid; falling back to English",
                Some(format!(
                    "key={} error={error}",
                    lorvex_domain::preference_keys::PREF_LANGUAGE
                )),
            );
            "en".to_string()
        }
    }
}

/// Translate a menu key for the given locale code.
///
/// Lookup is exact-locale-only: when an input like "zh-Hant" lacks a
/// translation, we fall through DIRECTLY to English rather than
/// stripping the region tag and probing the base ("zh").
///
/// #3051 H3 regression: the previous shape stripped the region tag and
/// tried the base on miss ("zh-Hant" → "zh"), but base fallback
/// assumes mutual intelligibility — true for "en-US" → "en" but FALSE
/// for "zh-Hant" → "zh" (different scripts) and similarly questionable
/// for "sr-Latn" → "sr" (Cyrillic) or "az-Latn" → "az" (Cyrillic). A
/// Traditional Chinese user with a partial zh-Hant table (Open /
/// QuickCapture / Quit) saw 3 Hant strings + 28 Simplified strings,
/// which is exactly the "hybrid surface" #3036 TR1 was meant to
/// prevent. Refuse the cross-script base fallback entirely; partial
/// language tables should fail through to English so the surface stays
/// consistent until the table is completed.
pub fn t(locale: &str, key: MenuKey) -> &'static str {
    if let Some(s) = lookup(locale, key) {
        return s;
    }
    // English fallback — see doc-comment for why we skip base-language
    // probing on a region-tagged miss.
    lookup("en", key).unwrap_or("?")
}

#[cfg(test)]
mod tests {
    use super::{
        append_menu_i18n_log_with_conn, parse_preferred_locale, preferred_locale_from_conn, t,
        MenuKey, MENU_I18N_LOG_SOURCE,
    };

    use crate::test_support::test_conn;

    #[test]
    fn append_menu_i18n_log_with_conn_persists_structured_diagnostic() {
        let conn = test_conn();

        append_menu_i18n_log_with_conn(
            &conn,
            "Warning",
            "Menu i18n diagnostic token=message-secret",
            Some("stage=test token=details-secret".to_string()),
        )
        .expect("append menu i18n diagnostic");

        let row: (String, String, String, Option<String>) = conn
            .query_row(
                "SELECT source, level, message, details FROM error_logs",
                [],
                |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?)),
            )
            .expect("read diagnostic row");

        assert_eq!(row.0, MENU_I18N_LOG_SOURCE);
        assert_eq!(row.1, "warn");
        assert_eq!(row.2, "Menu i18n diagnostic token=[REDACTED]");
        assert_eq!(row.3.as_deref(), Some("stage=test token=[REDACTED]"));
    }

    #[test]
    fn preferred_locale_from_conn_reads_canonical_language_preference() {
        let conn = test_conn();
        conn.execute(
            "INSERT INTO preferences (key, value, version, updated_at) VALUES (?1, ?2, ?3, ?4)",
            rusqlite::params![
                lorvex_domain::preference_keys::PREF_LANGUAGE,
                "\"zh-Hant\"",
                "0000000000000_0000_0000000000000000",
                "2026-03-29T00:00:00Z"
            ],
        )
        .expect("insert language preference");

        assert_eq!(
            preferred_locale_from_conn(&conn).expect("read locale"),
            Some("zh-Hant".to_string())
        );
    }

    #[test]
    fn preferred_locale_from_conn_rejects_malformed_language_preference() {
        let conn = test_conn();
        conn.execute(
            "INSERT INTO preferences (key, value, version, updated_at) VALUES (?1, ?2, ?3, ?4)",
            rusqlite::params![
                lorvex_domain::preference_keys::PREF_LANGUAGE,
                "not-json-string",
                "0000000000000_0000_0000000000000000",
                "2026-03-29T00:00:00Z"
            ],
        )
        .expect("insert malformed language preference");

        let error = preferred_locale_from_conn(&conn)
            .expect_err("malformed language preference should fail");
        assert!(error.contains("language"), "unexpected error: {error}");
    }

    #[test]
    fn parse_preferred_locale_accepts_json_string() {
        assert_eq!(
            parse_preferred_locale("\"zh-Hant\""),
            Some("zh-Hant".to_string())
        );
    }

    #[test]
    fn parse_preferred_locale_rejects_blank_json_string() {
        assert_eq!(parse_preferred_locale("\"   \""), None);
    }

    #[test]
    fn parse_preferred_locale_rejects_non_json_raw_string() {
        assert_eq!(parse_preferred_locale("en"), None);
    }

    /// #3051 M17 regression: a syntactically-valid JSON string that
    /// names an unknown locale (e.g. `"klingon"`, `"esperanto"`,
    /// `"qq-XX"`) must NOT pass through. The allowlist is the FE
    /// `localeRegistry` mirror — anything outside it is rejected at
    /// the trust boundary so corrupt or out-of-band preference values
    /// surface as `None` (caller falls back to English) instead of
    /// being silently stamped onto the menu rendering path.
    #[test]
    fn parse_preferred_locale_rejects_unknown_locale_codes() {
        assert_eq!(parse_preferred_locale("\"klingon\""), None);
        assert_eq!(parse_preferred_locale("\"esperanto\""), None);
        assert_eq!(parse_preferred_locale("\"qq-XX\""), None);
        assert_eq!(parse_preferred_locale("\"en-Latn-US-x-private\""), None);
    }

    /// Sanity: every entry in the FE registry mirror is accepted.
    #[test]
    fn parse_preferred_locale_accepts_every_known_locale_in_registry() {
        for code in super::KNOWN_LOCALES {
            let raw = format!("\"{code}\"");
            assert_eq!(
                parse_preferred_locale(&raw),
                Some((*code).to_string()),
                "FE-registry locale `{code}` must round-trip through parse_preferred_locale"
            );
        }
    }

    /// Regression: a region-tagged locale with no translation table
    /// at all must fall directly through to English rather than
    /// stripping the tag and probing the base. Stripping "zh-Hant"
    /// to "zh" would pull Simplified strings into a Traditional
    /// Chinese surface, producing a hybrid that violates the
    /// no-half-locale doctrine documented at the bottom of the
    /// lookup match. Every zh-Hant key falls through to English
    /// uniformly.
    #[test]
    fn zh_hant_falls_through_to_english_not_simplified() {
        assert_eq!(t("zh-Hant", MenuKey::Open), "Open Lorvex");
        assert_eq!(t("zh-Hant", MenuKey::Quit), "Quit");
        assert_eq!(t("zh-Hant", MenuKey::Today), "Today");
        assert_eq!(t("zh-Hant", MenuKey::Settings), "Settings\u{2026}");
        assert_eq!(t("zh-Hant", MenuKey::Help), "Lorvex Help");
        assert_eq!(t("zh-Hant", MenuKey::EisenhowerMatrix), "Eisenhower Matrix");
    }

    /// Sanity: bare "zh" (Simplified) still resolves to its full
    /// translation table. The H3 fix only removes the cross-script
    /// region→base fallback; it does NOT touch direct lookups.
    #[test]
    fn bare_zh_still_resolves_full_simplified_table() {
        assert_eq!(t("zh", MenuKey::Open), "打开 Lorvex");
        assert_eq!(t("zh", MenuKey::Today), "今天");
        assert_eq!(t("zh", MenuKey::Help), "Lorvex 帮助");
    }

    /// Region tags on languages with no translation table at all fall
    /// straight through to English (same as bare unknown locales).
    #[test]
    fn untranslated_region_tag_falls_through_to_english() {
        assert_eq!(t("pt-BR", MenuKey::Open), "Open Lorvex");
        assert_eq!(t("es-MX", MenuKey::Today), "Today");
    }
}
