//! Tauri plugin chain assembly.
//!
//! Centralized so `lib.rs::run` reads as a short orchestrator instead
//! of a long chain of `#[cfg(...)]`-gated `.plugin(...)` calls.
//!
//! Each `#[cfg]` arm in this module corresponds to a runtime
//! constraint:
//!
//! - `single_instance` / `window_state` / `deep_link` — desktop-only
//!   (mobile uses native multi-task primitives).
//! - `autostart` / `updater` — desktop distribution support.

use tauri::{Builder, Wry};

#[cfg(desktop)]
use crate::desktop_shell::handle_menu_event;
#[cfg(desktop)]
use crate::window_restore::focus_main_window;

/// Peel matching surrounding quotes and any number of nested quote
/// layers from a `--open-task` argument. A single
/// `strip_prefix('"').and_then(|s| s.strip_suffix('"'))` would only
/// undo one layer of quoting; a task ID generated by a shell that
/// re-quoted the arg (cmd.exe quirk: passing
/// `"--open-task \"<id>\""` through a `start` invocation can produce
/// `""<id>""`) would survive that single strip with surrounding
/// quotes still attached and fail the `task_id` validator. The
/// looped peeler below handles any nesting depth.
///
/// Strategy: trim ASCII whitespace, then loop peeling matched
/// `"`/`'` pairs until no surrounding quotes remain or the string
/// becomes empty. Mismatched pairs (one quote without the other)
/// are left intact so the validator rejects them with a clear
/// error rather than silently mangling the input.
#[cfg(desktop)]
pub(crate) fn strip_open_task_quotes(raw: &str) -> &str {
    let mut s = raw.trim();
    loop {
        let (Some(first), Some(last)) = (s.chars().next(), s.chars().next_back()) else {
            return s;
        };
        if (first == '"' || first == '\'') && first == last && s.len() >= 2 {
            // Both ends match the same quote char; peel one layer.
            // Use byte length because we matched on ASCII chars.
            s = &s[1..s.len() - 1];
            continue;
        }
        return s;
    }
}

/// scan a process's `argv` for the Jump List's
/// `--open-task <id>` deep-link and enqueue the corresponding
/// `DeepLinkTarget` so the renderer's pending-link consumer
/// dispatches the navigation. Used both at startup (the single-
/// instance plugin's primary-instance handler is not invoked when
/// the FIRST process launches) and on second-instance relaunch
/// (where it IS invoked, with the new process's argv).
///
/// Skips silently if no flag is present, so a normal cold launch
/// without arguments is a no-op. Validates the ID via the existing
/// `validate_task_id` so a hostile shortcut cannot inject a path
/// separator or control char into the queue.
#[cfg(desktop)]
pub(crate) fn enqueue_open_task_from_argv(
    argv: &[String],
) -> Option<crate::deep_link::DeepLinkTargetPayload> {
    for (i, arg) in argv.iter().enumerate() {
        let candidate: Option<&str> = if arg == "--open-task" {
            // `--open-task <id>` — the next argv slot carries the id.
            argv.get(i + 1).map(std::string::String::as_str)
        } else if let Some(rest) = arg.strip_prefix("--open-task=") {
            // GNU-style `--open-task=<id>` for completeness.
            Some(rest)
        } else if let Some(rest) = arg.strip_prefix("--open-task ") {
            // Single-string form `--open-task <id>` (rare, from
            // shells that pass a combined argv slot).
            Some(rest)
        } else {
            None
        };
        let Some(value) = candidate else {
            continue;
        };
        let value = strip_open_task_quotes(value);
        if value.is_empty() {
            continue;
        }
        match crate::deep_link::parse::validate_task_id(value, "task") {
            Ok(task_id) => {
                let target = crate::deep_link::DeepLinkTarget::Task { task_id };
                let payload = target.to_payload();
                crate::deep_link::enqueue_pending(target);
                return Some(payload);
            }
            Err(error) => {
                crate::deep_link::append_deep_link_log(
                    "warn",
                    "open_task_argv",
                    "ignored malformed --open-task argument",
                    Some(format!("value={value:?} error={error}")),
                );
                return None;
            }
        }
    }
    None
}

/// Build the always-present plugin chain.
fn install_universal_plugins(builder: Builder<Wry>) -> Builder<Wry> {
    builder
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_clipboard_manager::init())
}

#[cfg(desktop)]
fn install_desktop_plugins(builder: Builder<Wry>) -> Builder<Wry> {
    let builder = builder.plugin(tauri_plugin_single_instance::init(
        |app_handle, argv, _cwd| {
            // A Jump List click on Windows launches a second instance
            // with `--open-task <id>` in argv. Parse the flag here,
            // enqueue a `DeepLinkTarget::Task`, and emit the standard
            // deep-link event so the renderer's pending-link consumer
            // dispatches the navigation through the same path used
            // by the macOS `RunEvent::Opened` flow. Ignoring argv
            // would let a Jump List entry focus the window without
            // navigating to the task.
            if let Some(payload) = enqueue_open_task_from_argv(&argv) {
                use tauri::Emitter;
                let _ = app_handle.emit(crate::deep_link::DEEP_LINK_OPEN_EVENT, payload);
            }
            // Always focus the main window so the user sees the
            // navigation result rather than an unresponsive desktop
            // shortcut click.
            focus_main_window(app_handle, "single_instance_relaunch");
        },
    ));

    let window_state_flags = tauri_plugin_window_state::StateFlags::all()
        & !tauri_plugin_window_state::StateFlags::VISIBLE;
    let builder = builder.plugin(
        tauri_plugin_window_state::Builder::default()
            .with_state_flags(window_state_flags)
            .with_denylist(&["popover"])
            .build(),
    );

    builder.plugin(tauri_plugin_deep_link::init())
}

#[cfg(not(desktop))]
fn install_desktop_plugins(builder: Builder<Wry>) -> Builder<Wry> {
    builder
}

#[cfg(desktop)]
fn install_distribution_plugins(builder: Builder<Wry>) -> Builder<Wry> {
    builder
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            None,
        ))
        .plugin(tauri_plugin_updater::Builder::new().build())
}

#[cfg(not(desktop))]
fn install_distribution_plugins(builder: Builder<Wry>) -> Builder<Wry> {
    builder
}

#[cfg(desktop)]
fn install_menu_handler(builder: Builder<Wry>) -> Builder<Wry> {
    builder.on_menu_event(handle_menu_event)
}

#[cfg(not(desktop))]
fn install_menu_handler(builder: Builder<Wry>) -> Builder<Wry> {
    builder
}

#[cfg(all(test, desktop))]
mod tests {
    use super::strip_open_task_quotes;

    #[test]
    fn strip_open_task_quotes_handles_unquoted_input() {
        assert_eq!(strip_open_task_quotes("abc"), "abc");
    }

    #[test]
    fn strip_open_task_quotes_peels_single_double_quote_pair() {
        assert_eq!(strip_open_task_quotes("\"abc\""), "abc");
    }

    #[test]
    fn strip_open_task_quotes_peels_nested_double_quote_pairs() {
        // The cmd.exe `start` quirk wraps a quoted argument in
        // another quote layer; a single-strip implementation would
        // leave the inner quotes attached. The looped peeler must
        // walk through both layers.
        assert_eq!(strip_open_task_quotes("\"\"abc\"\""), "abc");
    }

    #[test]
    fn strip_open_task_quotes_peels_mixed_layered_quotes() {
        // Outer single-quote wrap, inner double-quote wrap (the
        // PowerShell `Start-Process -ArgumentList "'<id>'"` shape).
        assert_eq!(strip_open_task_quotes("'\"abc\"'"), "abc");
    }

    #[test]
    fn strip_open_task_quotes_leaves_mismatched_quote_alone() {
        // A leading `"` without a trailing `"` is malformed input;
        // leave it to the validator so the caller surfaces a clear
        // error instead of silently mangling the value.
        assert_eq!(strip_open_task_quotes("\"abc"), "\"abc");
        assert_eq!(strip_open_task_quotes("abc\""), "abc\"");
    }

    #[test]
    fn strip_open_task_quotes_trims_surrounding_whitespace() {
        assert_eq!(strip_open_task_quotes("  \"abc\"  "), "abc");
    }

    #[test]
    fn strip_open_task_quotes_handles_empty_and_quote_only() {
        assert_eq!(strip_open_task_quotes(""), "");
        // `""` peels to empty; `"""` peels to one stray quote.
        assert_eq!(strip_open_task_quotes("\"\""), "");
        assert_eq!(strip_open_task_quotes("\"\"\""), "\"");
    }
}

/// Compose the full plugin chain in the order each subsystem expects.
pub(crate) fn install_plugins(builder: Builder<Wry>) -> Builder<Wry> {
    let builder = install_universal_plugins(builder);
    let builder = install_desktop_plugins(builder);
    let builder = install_distribution_plugins(builder);
    install_menu_handler(builder)
}
