//! Forward-compat payload-shadow promotion.
//!
//! Once the local schema understands a payload version that was
//! shadowed (because the receiving device was on an older schema when
//! the envelope first arrived), the shadow row needs to land in the
//! canonical table just as if the envelope had arrived under today's
//! schema. The path here mirrors the apply pipeline: tombstone-
//! redirect chase → tombstone-on-target check → LWW /
//! obsolete-shadow gate → FK preflight → dispatch — all keyed on the
//! resolved redirect-terminus identity rather than the shadow's
//! original id.

use rusqlite::Connection;

use lorvex_domain::hlc::Hlc;
use lorvex_domain::version::PAYLOAD_SCHEMA_VERSION;

use super::envelope::{apply_entity_with_version_mode, check_fk_dependencies, get_local_version};
use super::redirect::chase_redirect_chain;
use super::{ApplyError, DeferralReason, LwwTieBreak};
use crate::envelope::{SyncEnvelope, SyncOperation};
use crate::tombstone::get_tombstone;

/// Promote any payload shadows whose schema version is now fully understood
/// into the canonical tables, then clear the shadow rows.
///
/// Promotion routes through `apply_envelope` (not the raw
/// `apply_entity_with_version_mode`) so the tombstone-redirect chain is
/// resolved upfront. A shadowed payload authored before a
/// tag/recurrence merge would otherwise land on the merge LOSER's id
/// (a phantom row) and be purged by `remove_shadow_if_superseded`,
/// silently dropping the user's edits during forward-compat promotion.
/// The envelope is applied at the redirect target with the original
/// peer's `device_id` carried over from the shadow row, so any
/// conflict_log entry written during promotion attributes truncation
/// / LWW losses to the real peer.
pub fn promote_payload_shadows(conn: &Connection) -> Result<usize, ApplyError> {
    // capture the apply timestamp ONCE at promote
    // entry. Every shadow row's promotion shares the same moment of
    // apply for conflict-log / cascade-tombstone correlation.
    let apply_ts = lorvex_domain::sync_timestamp_now();
    let mut promoted = 0usize;
    // Wrap each shadow row's promotion in a SAVEPOINT.
    //
    // Running every shadow's tombstone-chase, FK preflight, LWW gate,
    // `apply_entity_with_version_mode`, and `remove_shadow_if_superseded`
    // directly against the outer transaction would tear down the entire
    // batch on any single mid-batch failure (FK violation surfaced late,
    // malformed payload caught only inside a child handler, panic-on-
    // unwrap in a downstream helper). Every prior shadow successfully
    // promoted in this pass would roll back with it, even though those
    // rows were independently correct. After the rollback the shadows
    // would still exist and the next promote pass would re-process them
    // all, burning cycles and re-running side effects (conflict_log
    // inserts, error_log inserts, tombstone churn).
    //
    // A per-row SAVEPOINT isolates each shadow so a single bad row only
    // loses ITS work; the surrounding transaction and every other
    // promoted row stay committed.
    //
    // The savepoint name is generated by `with_savepoint_mapped` from
    // a process-wide atomic counter (see
    // `lorvex_store::transaction::savepoint::SAVEPOINT_COUNTER`),
    // matching every other savepoint in the apply pipeline
    // (`cycle_break_and_insert_*`, `merge_tags_*`, `merge_recurrence_*`).
    // Keying on the row's enumerate index would let a future nested
    // apply path that re-enters `promote_payload_shadows` collide on
    // `promote_payload_shadow_0` and either RELEASE the wrong savepoint
    // or trip a SQLite syntax error mid-transaction. The monotonic
    // counter keeps names unique even across arbitrarily-deep recursive
    // entries within the same outer transaction.
    for row in lorvex_sync_payload::payload_shadow::list_shadows(conn)? {
        if row.payload_schema_version > PAYLOAD_SCHEMA_VERSION {
            continue;
        }

        // Wrap each per-shadow attempt in a savepoint so a partial
        // failure rolls back JUST this row's writes — the outer txn
        // stays intact so previously-promoted shadows survive, and
        // the bad shadow row remains in `payload_shadows` for a
        // future promote pass to retry once whatever caused the
        // failure is fixed. Routes through
        // `lorvex_store::transaction::with_savepoint_mapped` so a
        // panic inside `promote_one_shadow` rolls the savepoint back
        // before the unwind resumes (the hand-rolled
        // `SAVEPOINT … ; RELEASE` shape would have left the
        // savepoint dangling).
        match lorvex_store::transaction::with_savepoint_mapped(
            conn,
            "promote_payload_shadow",
            ApplyError::InvalidPayload,
            |conn| promote_one_shadow(conn, &row, &apply_ts),
        ) {
            Ok(true) => promoted += 1,
            Ok(false) => {
                // The shadow was handled (skipped, dropped, etc.)
                // but no canonical-table promotion ran. The helper
                // already released the savepoint so incidental
                // writes (shadow row removal, conflict log inserts)
                // commit alongside the surrounding transaction.
            }
            Err(err) => {
                let detail = format!(
                    "shadow promotion failed for {}:{} version {}: {err}",
                    row.entity_type.as_str(),
                    row.entity_id,
                    row.base_version
                );
                crate::error_log::log_sync_error(
                    conn,
                    "sync.apply.promote_shadow_failed",
                    &detail,
                    None,
                );
            }
        }
    }
    Ok(promoted)
}

/// Promote a single payload-shadow row. Returns `Ok(true)` when the
/// shadow was successfully promoted into a canonical row; `Ok(false)`
/// when the shadow was handled by a non-promote path (forward-compat
/// version mismatch, tombstoned-target drop, FK preflight defer,
/// LWW-loser drop). Errors propagate so the caller can roll the
/// per-row SAVEPOINT back without taking down the whole batch.
///
/// Each call's SAVEPOINT scope is exactly one shadow's writes, so the
/// caller can roll a single bad row back without taking down the
/// surrounding batch.
fn promote_one_shadow(
    conn: &Connection,
    row: &lorvex_sync_payload::payload_shadow::PayloadShadowRow,
    apply_ts: &str,
) -> Result<bool, ApplyError> {
    // Resolve any tombstone first so we know whether the shadow
    // points at a redirect target, an absolute deletion, or a
    // live row.
    let initial_ts = get_tombstone(conn, row.entity_type.as_str(), &row.entity_id)?;
    // Track the entity_type alongside the id so a cross-type chain
    // hop (task→habit, parent→memory) lands the shadow promotion
    // on the right table — re-reading tombstones at
    // `&row.entity_type` after a cross-type redirect would silently
    // route the promotion to the wrong table.
    //
    // `(promote_type, promote_id)` is built once from whichever
    // branch fires so the no-redirect path is the only one that
    // allocates; the redirect branch routes the already-owned
    // `chase_redirect_chain` results through directly.
    let (promote_type, promote_id) = match initial_ts {
        Some(ts) if ts.redirect_entity_id.is_some() => {
            // Walk the redirect chain via the shared helper so the
            // promote-shadow walk and `apply_envelope`'s walk share
            // one canonical (cap, cycle, deep-chain, cross-type)
            // implementation.
            let (final_type, final_id, _hops) =
                chase_redirect_chain(conn, row.entity_type.as_str(), &row.entity_id)?;
            (final_type, final_id)
        }
        Some(_) => {
            // Absolute deletion at the original id — drop the
            // shadow so it can't resurrect the deleted entity.
            lorvex_sync_payload::payload_shadow::remove_shadow(
                conn,
                row.entity_type.as_str(),
                &row.entity_id,
            )?;
            return Ok(false);
        }
        None => (row.entity_type.as_str().to_string(), row.entity_id.clone()),
    };

    // Parse the shadow's `base_version` once. Storage holds
    // canonical HLC strings, so a parse failure here is corruption
    // that survived `upsert_shadow`'s checks. Map it to the
    // pipeline's `InvalidVersion` so the promotion attempt surfaces
    // the corruption diagnostically. The parse happens exactly once
    // and is reused by both the synthetic device-id derivation below
    // and the envelope construction.
    let base_hlc = Hlc::parse(&row.base_version)?;

    let device_id = if row.source_device_id.is_empty() {
        // Shadow rows with no recorded device_id derive a best-effort
        // device attribution from the canonical HLC's 8-char
        // lowercase-hex `device_suffix` field. The
        // `"shadow-suffix:"` prefix keeps the synthetic-vs-real
        // distinction visible to the diagnostics surface (a real
        // device_id is a UUIDv4 with hyphens; the suffix-derived
        // form is exactly 23 chars = `shadow-suffix:` [14] + 8-hex
        // [8] = unambiguous prefix-disambig).
        format!("shadow-suffix:{}", base_hlc.device_suffix())
    } else {
        row.source_device_id.clone()
    };

    // Route the synthesized envelope at `promote_type` rather than
    // `row.entity_type` so a cross-type redirect chase (task→habit,
    // parent→memory) lands the promotion on the correct table.
    // `promote_type` is the redirect terminus of the
    // shadow row, which is stored as TEXT in the payload-shadow table.
    // Parse into the typed `EntityKind` for the synthesized envelope —
    // a shadow promotion onto an unknown kind is a schema-side
    // invariant violation, not a forward-compat case.
    let envelope = SyncEnvelope {
        entity_type: lorvex_domain::naming::EntityKind::parse(&promote_type).ok_or_else(|| {
            ApplyError::UnknownEntityType(format!(
                "shadow promotion target has unknown entity_type: {promote_type}"
            ))
        })?,
        entity_id: promote_id.clone(),
        operation: SyncOperation::Upsert,
        version: base_hlc,
        payload_schema_version: row.payload_schema_version,
        payload: row.raw_payload_json.clone(),
        device_id,
    };

    // mirror the `apply_envelope` guards on the
    // resolved `promote_id`. Without these, a shadow whose
    // `base_version` happens to equal a current row's version (or
    // sit on a redirect target that was hard-deleted between merge
    // and promotion) would either resurrect the deletion, overwrite
    // newer local state, or INSERT against a missing FK parent —
    // each of which is a durable corruption of peer-converged
    // state. The order matches `apply_envelope`: tombstone check →
    // LWW / obsolete-shadow gate → FK preflight, all keyed on
    // `promote_id` rather than the shadow's original id.

    // (a) Non-redirect tombstone at (promote_type, promote_id):
    //     shadow can't resurrect a deletion. Drop the shadow.
    // probe at `promote_type` (which may differ
    //     from the shadow's original entity_type when the chain
    //     crossed types) so cross-type tombstones are honored.
    if let Some(target_ts) = crate::tombstone::get_tombstone(conn, &promote_type, &promote_id)? {
        if target_ts.redirect_entity_id.is_none() {
            let target_ts_version = Hlc::parse(&target_ts.version)?;
            // `envelope.version` is typed `Hlc`.
            let envelope_version = &envelope.version;
            if envelope_version <= &target_ts_version {
                // The shadow row itself is keyed at
                // `(row.entity_type, row.entity_id)` in
                // `payload_shadows` regardless of where the chase
                // landed, so removal still uses the original
                // (pre-redirect) identity.
                lorvex_sync_payload::payload_shadow::remove_shadow(
                    conn,
                    row.entity_type.as_str(),
                    &row.entity_id,
                )?;
                return Ok(false);
            }
            // Shadow is strictly newer than the delete tombstone
            // (concurrent-update-wins-over-concurrent-delete). Lift
            // the tombstone and fall through to apply the shadow,
            // matching the `apply_envelope` redirect path.
            crate::tombstone::remove_tombstone(conn, &promote_type, &promote_id)?;
        }
    }

    // (b) LWW gate against the live row at promote_id.
    //
    // The gate runs for BOTH the redirect and non-redirect paths so
    // the shadow's `base_version` is always compared against the
    // local row's current version. Routing the non-redirect case
    // straight through to `apply_entity_with_version_mode(_, true)`
    // (`>=` semantics) would rely on the implicit invariant
    // "shadow.base_version >= row.version", which only holds when
    // `remove_shadow_if_superseded` has run after every newer
    // envelope; Skipped paths do not always run that helper, and a
    // broken invariant would let the SQL `excluded.version >= row.version`
    // gate silently refuse the INSERT, reap the shadow, and
    // permanently lose the forward-compat fields the shadow was
    // preserving with no diagnostic.
    //
    // Decision matrix on the typed `LwwTieBreak`:
    //  - `LocalWins` (local strictly newer than shadow): log a
    //    `shadow_obsolete` conflict, drop the shadow, do not INSERT.
    //  - equal versions: legitimate rehydrate-after-schema-upgrade
    //    case — fall through and let
    //    `apply_entity_with_version_mode(_, true)` do its work with
    //    `>=` semantics.
    //  - `RemoteWins`: rare for the non-redirect path but legitimate
    //    for the redirect path (a pre-merge shadow whose HLC
    //    dominates the post-merge row's). Fall through to apply.
    if let Some((local_version_str, local_version)) =
        parse_local_version_for_shadow_gate(conn, &envelope)?
    {
        // `envelope.version` is typed `Hlc`.
        let remote_version = &envelope.version;
        // Use STRICT comparison so the legitimate
        // "rehydrate-after-schema-upgrade" case (where the live
        // row's version equals the shadow's base_version) falls
        // through to apply with `>=` semantics. `resolve_lww`
        // tie-breaks equal versions to LocalWins for idempotent
        // re-apply, which is correct for inbound envelopes but
        // wrong here — equal version means the shadow IS for the
        // current row, and promotion must be allowed.
        if &local_version > remote_version {
            // this row uses `RESOLUTION_SHADOW_OBSOLETE`
            // — a SEMANTICALLY DIFFERENT outcome from a normal LWW
            // loss. The diagnostics-feed UI already renders
            // `entry.kind` raw (DiagnosticsPanel.tsx line ~514) so
            // both surfaces are visually distinguishable today, but
            // the distinction is worth re-stating at the write site:
            //
            //   - `RESOLUTION_LWW`: an inbound peer envelope lost a
            //     standard last-writer-wins comparison against the
            //     local live row. The peer's content is preserved
            //     in `loser_payload` for replay/inspection.
            //   - `RESOLUTION_SHADOW_OBSOLETE`: a forward-compat
            //     payload shadow (`sync_payload_shadows`) that was
            //     captured under an older schema's parser is being
            //     reaped because the live row has already advanced
            //     past it. The shadow's preserved unknown fields
            //     are LOST when this row is written — there is no
            //     mechanism to re-extract them post-reap. Operators
            //     who see this resolution_type should read it as
            //     "forward-compat unknown data was dropped because
            //     a newer canonical edit superseded the shadow,"
            //     not "two peers' edits collided."
            //
            // If the UI ever grows a per-resolution-type filter or
            // affordance, `shadow_obsolete` should sort under a
            // distinct heading (e.g. "Forward-compat shadow drops")
            // rather than be lumped with LWW outcomes.
            crate::conflict_log::log_conflict(
                conn,
                &crate::conflict_log::ConflictLogEntry {
                    id: 0,
                    entity_type: std::borrow::Cow::Borrowed(envelope.entity_type.as_str()),
                    entity_id: envelope.entity_id.clone(),
                    winner_version: local_version_str,
                    loser_version: envelope.version.to_string(),
                    loser_device_id: envelope.device_id.clone(),
                    loser_payload: Some(envelope.payload.clone()),
                    resolved_at: apply_ts.to_string(),
                    resolution_type: std::borrow::Cow::Borrowed(
                        lorvex_domain::naming::RESOLUTION_SHADOW_OBSOLETE,
                    ),
                },
            )?;
            lorvex_sync_payload::payload_shadow::remove_shadow(
                conn,
                row.entity_type.as_str(),
                &row.entity_id,
            )?;
            return Ok(false);
        }
    }

    // (c) FK preflight: any missing parent means the shadow can't
    //     promote yet. This runs after the obsolete-shadow gate so a
    //     stale shadow whose payload also references a missing parent
    //     is logged and reaped as `shadow_obsolete` rather than parked
    //     in pending inbox indefinitely.
    //
    //     This branch must NOT silently leave the shadow in place and
    //     return `Ok(false)`. A stuck shadow handled that way would be
    //     invisible to the rest of the sync pipeline — the diagnostics
    //     surface (Settings → Diagnostics → Pending Envelopes) would
    //     have no row for it, the FK-arrival drain trigger could not
    //     pick it up, and a long-tail missing dependency would tie the
    //     shadow up indefinitely until the next periodic promote pass.
    //     Mirror the orchestration `apply_envelope` does for inbound
    //     envelopes: enqueue the synthesized envelope into
    //     `sync_pending_inbox` so the FK-arrival drain can replay it
    //     as soon as the parent lands. The enqueue is upsert-keyed on
    //     `(entity_type, entity_id, version)` so repeated promote
    //     passes do not flood the inbox — duplicate calls just bump
    //     `attempt_count` on the existing row. The shadow is also left
    //     intact so the durable forward-compat payload survives a
    //     schema upgrade in flight; the eventual
    //     `apply_envelope` replay will clear the shadow via
    //     `finalize_payload_shadow` once the FK target arrives.
    if let Some((dep_type, dep_id)) = check_fk_dependencies(
        conn,
        envelope.entity_type.as_str(),
        &envelope.entity_id,
        &envelope.payload,
    )? {
        let reason = DeferralReason::MissingDependency {
            entity_type: dep_type,
            entity_id: dep_id,
        };
        crate::pending_inbox::enqueue_deferred(conn, &envelope, &reason).map_err(|e| match e {
            crate::error::SyncError::Sql(sql_err) => ApplyError::Db(sql_err),
            other => ApplyError::InvalidPayload(format!(
                "failed to enqueue shadow promotion to pending inbox: {other}"
            )),
        })?;
        return Ok(false);
    }

    apply_entity_with_version_mode(conn, &envelope, LwwTieBreak::AllowEqual, apply_ts)?;
    // Always clear the shadow at the ORIGINAL id (the table is
    // keyed there). `promote_id` may differ if a redirect chase
    // happened above, but the shadow row to remove is the one
    // we read at the top of the loop.
    lorvex_sync_payload::payload_shadow::remove_shadow_if_superseded(
        conn,
        row.entity_type.as_str(),
        &row.entity_id,
        &row.base_version,
    )?;
    Ok(true)
}

fn parse_local_version_for_shadow_gate(
    conn: &Connection,
    envelope: &SyncEnvelope,
) -> Result<Option<(String, Hlc)>, ApplyError> {
    let Some(local_version_str) =
        get_local_version(conn, envelope.entity_type.as_str(), &envelope.entity_id)?
    else {
        return Ok(None);
    };

    match Hlc::parse(&local_version_str) {
        Ok(local_version) => Ok(Some((local_version_str, local_version))),
        Err(err) => {
            let detail = format!(
                "local version '{local_version_str}' on {}:{} is not a valid HLC: {err}",
                envelope.entity_type, envelope.entity_id
            );
            crate::error_log::log_sync_error(
                conn,
                "sync.apply.local_version_corruption",
                &detail,
                None,
            );
            Ok(None)
        }
    }
}
